# -*- coding: utf-8 -*-
"""既知パラメータの合成 G-code を生成し、復元精度を検証するための素材を作る。"""
import math, os

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "sample_synth")
os.makedirs(OUT, exist_ok=True)

DIA = 1.75
AREA = math.pi * (DIA / 2) ** 2

def e_for(length, w, h):
    return (w * h * length) / AREA

def square(cx, cy, half):
    return [(cx-half, cy-half), (cx+half, cy-half), (cx+half, cy+half),
            (cx-half, cy+half), (cx-half, cy-half)]

# ---------------------------------------------------------------------------
# PrusaSlicer 風: ;TYPE: + ;WIDTH:/;HEIGHT: + 末尾 config ブロック / 相対E(M83)
# ---------------------------------------------------------------------------
def make_prusa():
    LH, FLH, W = 0.2, 0.2, 0.45
    OW, IW = 25.0, 80.0   # outer/infill speed mm/s -> F
    L = []
    L += ["; generated by PrusaSlicer 2.7.1 on 2026-06-30",
          "M104 S215", "M140 S60", "M109 S215", "M190 S60",
          "G21", "G90", "M83", "G92 E0"]
    z = 0.0
    for layer in range(5):
        z = round(FLH + layer*LH, 3) if layer else FLH
        L += [";LAYER_CHANGE", f";Z:{z}", f";HEIGHT:{LH if layer else FLH}", f"G1 Z{z} F9000"]
        # 外周(2ループ)
        L += [";TYPE:External perimeter", f";WIDTH:{W}", f"G1 F{OW*60:.0f}"]
        pts = square(100, 100, 20)
        L.append(f"G1 X{pts[0][0]} Y{pts[0][1]}")
        for (x1,y1),(x0,y0) in zip(pts[1:], pts[:-1]):
            seg = math.hypot(x1-x0, y1-y0)
            L.append(f"G1 X{x1} Y{y1} E{e_for(seg,W,LH):.5f}")
        # インフィル(平行線)
        L += [";TYPE:Internal infill", f";WIDTH:{W}", f"G1 F{IW*60:.0f}"]
        y = 82
        while y <= 118:
            L.append(f"G1 X82 Y{y}")
            L.append(f"G1 X118 Y{y} E{e_for(36,W,LH):.5f}")
            y += 2  # ライン間隔2mm -> 密度 ~ W/2=22.5%
        # リトラクト(相対E)
        L.append("G1 E-0.8 F2100")
        L.append("G1 E0.8 F1500")
    cfg = [
        "; prusaslicer_config = begin",
        "; layer_height = 0.2", "; first_layer_height = 0.2",
        "; perimeter_speed = 45", "; external_perimeter_speed = 25",
        "; infill_speed = 80", "; solid_infill_speed = 60",
        "; top_solid_infill_speed = 40", "; travel_speed = 180",
        "; perimeters = 3", "; fill_density = 20%", "; fill_pattern = gyroid",
        "; temperature = 215", "; bed_temperature = 60",
        "; retract_length = 0.8", "; retract_speed = 35", "; deretract_speed = 25",
        "; retract_lift = 0.4", "; support_material = 0", "; filament_diameter = 1.75",
        "; external_perimeter_extrusion_width = 0.45",
        "; perimeter_extrusion_width = 0.45", "; infill_extrusion_width = 0.45",
        "; max_fan_speed = 100",
        "; prusaslicer_config = end",
    ]
    L += cfg
    return "\n".join(L) + "\n"

# ---------------------------------------------------------------------------
# Cura 風: ;TYPE:WALL-OUTER/FILL + ;LAYER: / 絶対E(M82) / 設定ブロック無し / G0トラベル
# ---------------------------------------------------------------------------
def make_cura():
    LH, W = 0.28, 0.5
    e = 0.0
    L = [";FLAVOR:Marlin", ";Generated with Cura_SteamEngine 5.6.0",
         "M104 S210", "M140 S60", "M109 S210", "M190 S60",
         "G21", "G90", "M82", "G92 E0", ";LAYER_COUNT:5"]
    for layer in range(5):
        z = round(LH*(layer+1), 3)
        L += [f";LAYER:{layer}", f"G0 F9000 Z{z}"]
        L += [";TYPE:WALL-OUTER", "G1 F1500"]
        pts = square(120, 120, 15)
        L.append(f"G0 X{pts[0][0]} Y{pts[0][1]}")
        for (x1,y1),(x0,y0) in zip(pts[1:], pts[:-1]):
            seg = math.hypot(x1-x0, y1-y0); e += e_for(seg, W, LH)
            L.append(f"G1 X{x1} Y{y1} E{e:.5f}")
        L += [";TYPE:FILL", "G1 F3000"]
        y = 107
        while y <= 133:
            L.append(f"G0 X107 Y{y}")
            e += e_for(26, W, LH)
            L.append(f"G1 X133 Y{y} E{e:.5f}")
            y += 2
        # 絶対Eリトラクト
        L.append(f"G1 F2400 E{e-6.5:.5f}")
        L.append(f"G1 F2400 E{e:.5f}")
    return "\n".join(L) + "\n"

# ---------------------------------------------------------------------------
# Klipper/RepRap 風: 円弧 G2/G3 + M207 ファーム内リトラクト / TYPEマーカー無し(幾何のみ)
# ---------------------------------------------------------------------------
def make_klipper():
    LH, W = 0.2, 0.4
    L = ["; Klipper / RepRap dialect sample", "G21", "G90", "M83",
         "M207 S1.2 F2400 Z0.3"]
    for layer in range(4):
        z = round(LH*(layer+1), 3)
        L.append(f"G1 Z{z} F600")
        # 円(半径10)を G2 で一周: 中心(150,150) 始点(160,150)
        L.append("G1 X160 Y150 F1200")
        circ = 2*math.pi*10
        L.append(f"G2 X160 Y150 I-10 J0 E{e_for(circ,W,LH):.5f} F1200")
        # 直線インフィル
        L.append("G1 X145 Y145 F3000")
        L.append(f"G1 X155 Y155 E{e_for(math.hypot(10,10),W,LH):.5f}")
        # ファーム内リトラクト
        L.append("G10")
        L.append("G11")
    return "\n".join(L) + "\n"

# ---------------------------------------------------------------------------
# マルチフィラメント風: 2ツール、ツール毎に温度違い + ツールチェンジ列 (PrusaSlicer系)
# ---------------------------------------------------------------------------
def make_mmu():
    LH, W = 0.2, 0.45
    L = ["; generated by PrusaSlicer 2.7.1 (MMU)",
         "M104 S210 T0", "M104 S240 T1",
         "G21", "G90", "M83", "G92 E0",
         "T0", "M109 S210 T0"]
    z = 0.0
    for layer in range(4):
        z = round(LH*(layer+1), 3)
        L += [";LAYER_CHANGE", f";Z:{z}", f";HEIGHT:{LH}", f"G1 Z{z} F9000"]
        # ツール0 で四角
        L += [";TYPE:Perimeter", f";WIDTH:{W}", "G1 F1500"]
        pts = square(100, 100, 15)
        L.append(f"G1 X{pts[0][0]} Y{pts[0][1]}")
        for (x1,y1),(x0,y0) in zip(pts[1:], pts[:-1]):
            L.append(f"G1 X{x1} Y{y1} E{e_for(math.hypot(x1-x0,y1-y0),W,LH):.5f}")
        # --- ツールチェンジ T0->T1 ---
        L += ["G1 E-2.0 F2400",          # リトラクト
              "T1",                       # 工具切替
              "M109 S240 T1",             # T1 加熱待ち
              "G1 X90 Y90 F9000",         # ワイプ移動
              "G1 E2.0 F1500"]            # デリトラクト
        # ツール1 で別四角
        L += [";TYPE:Perimeter", f";WIDTH:{W}", "G1 F1500"]
        pts = square(140, 140, 15)
        L.append(f"G1 X{pts[0][0]} Y{pts[0][1]}")
        for (x1,y1),(x0,y0) in zip(pts[1:], pts[:-1]):
            L.append(f"G1 X{x1} Y{y1} E{e_for(math.hypot(x1-x0,y1-y0),W,LH):.5f}")
        L += ["G1 E-2.0 F2400", "T0", "M109 S210 T0", "G1 E2.0 F1500"]
    L += ["M104 S0 T0", "M104 S0 T1", "M140 S0", "; layer_height = 0.2",
          "; temperature = 210,240", "; perimeters = 1", "; fill_density = 15%"]
    return "\n".join(L) + "\n"

for name, gen in [("prusa_synth.gcode", make_prusa),
                  ("cura_synth.gcode", make_cura),
                  ("klipper_synth.gcode", make_klipper),
                  ("mmu_synth.gcode", make_mmu)]:
    p = os.path.join(OUT, name)
    with open(p, "w", encoding="utf-8") as fh:
        fh.write(gen())
    print("wrote", p)
