# -*- coding: utf-8 -*-
"""Phase 6 native importer tests."""
import json
import os
import zipfile

import pytest

from gcode_profiler import importers
from gcode_profiler.importers import (
    detection, json_family, ini_family, xml_family, inheritance, merge,
    to_canonical, security,
)
from gcode_profiler.importers.repository import Repository
from gcode_profiler.canonical import model as m


# ---------------------------------------------------------------------------
# fixtures
# ---------------------------------------------------------------------------
def _write(tmp_path, name, text):
    p = os.path.join(str(tmp_path), name)
    with open(p, "w", encoding="utf-8") as f:
        f.write(text)
    return p


ORCA_CHILD = json.dumps({
    "type": "process",
    "name": "0.20mm Fine",
    "inherits": "0.20mm Base",
    "version": "2.3.0.0",
    "outer_wall_speed": ["120"],
    "sparse_infill_density": "18%",
    "wall_loops": "3",
})

ORCA_PARENT = json.dumps({
    "type": "process",
    "name": "0.20mm Base",
    "layer_height": "0.2",
    "outer_wall_speed": ["80"],
    "sparse_infill_density": "15%",
    "some_orca_only_key": "keepme",
})

PRUSA_INI = """\
; generated by PrusaSlicer 2.6.0
layer_height = 0.2
first_layer_height = 0.24
perimeters = 3
fill_density = 20%
external_perimeter_speed = 30
perimeter_speed = 60
temperature = 215
bed_temperature = 60
nozzle_diameter = 0.4
weird_prusa_key = 12
"""

CURA_CFG = """\
[general]
version = 4
name = My Quality
definition = ultimaker3
[metadata]
type = quality_changes
setting_version = 20
[values]
layer_height = 0.15
wall_line_count = 4
infill_sparse_density = 25
speed_wall_0 = 40
material_print_temperature = 205
"""

S3D_FFF = """\
<?xml version="1.0"?>
<profile name="MyPLA" version="5.0.0">
  <layerHeight>0.2</layerHeight>
  <perimeterOutlines>2</perimeterOutlines>
  <infillPercentage>15</infillPercentage>
  <defaultSpeed>3600</defaultSpeed>
  <extruderWidth>0.48</extruderWidth>
</profile>
"""


# ===========================================================================
# 1. detection (content-based, not extension-only)
# ===========================================================================
def test_detect_orca_json_by_content(tmp_path):
    p = _write(tmp_path, "weird.txt", ORCA_CHILD)   # wrong extension on purpose
    det = importers.detect(p)
    assert det["slicer"] == "OrcaSlicer"
    assert det["format"] == "json"
    assert det["profile_kind"] == "process"


def test_detect_prusa_ini_by_content(tmp_path):
    p = _write(tmp_path, "cfg.dat", PRUSA_INI)
    det = importers.detect(p)
    assert det["slicer"] in ("PrusaSlicer", "SuperSlicer")
    assert det["format"] == "ini"


def test_detect_cura_cfg(tmp_path):
    p = _write(tmp_path, "q.inst.cfg", CURA_CFG)
    det = importers.detect(p)
    assert det["slicer"] == "Cura"


def test_detect_simplify3d_fff(tmp_path):
    p = _write(tmp_path, "prof.fff", S3D_FFF)
    det = importers.detect(p)
    assert det["slicer"] == "Simplify3D"


def test_detect_unknown_content():
    det = detection.detect_text("just some random text\nno markers here")
    assert det["confidence"] == 0.0


# ===========================================================================
# 2. parsers preserve representation
# ===========================================================================
def test_json_parser_keeps_percentage_distinct():
    prof = json_family.parse_json(ORCA_PARENT, "x.json", "OrcaSlicer")
    dens = prof.raw_fields["sparse_infill_density"]
    assert dens.value_mode == "percentage"
    assert dens.parsed_value == 15.0
    lh = prof.raw_fields["layer_height"]
    assert lh.parsed_value == 0.2 and lh.value_mode == "absolute"


def test_ini_parser_flat_and_comments():
    prof = ini_family.parse_ini(PRUSA_INI, "x.ini", "PrusaSlicer")
    assert "layer_height" in prof.raw_fields
    assert prof.raw_fields["fill_density"].value_mode == "percentage"
    assert any("PrusaSlicer" in c for c in prof.comments)


def test_ini_parser_bundle_splits_sections():
    bundle = ini_family.parse_ini(
        "[print:Fast]\nlayer_height = 0.3\n[filament:PLA]\ntemperature = 200\n",
        "b.ini", "PrusaSlicer")
    assert bundle.profile_kind == "bundle"
    kinds = {s.profile_kind for s in bundle.sub_profiles}
    assert kinds == {"process", "filament"}


def test_xml_parser_reads_leaf_elements():
    prof = xml_family.parse_xml(S3D_FFF, "p.fff", "Simplify3D")
    assert prof.raw_fields["layerHeight"].parsed_value == 0.2
    assert prof.raw_fields["perimeterOutlines"].parsed_value == 2


# ===========================================================================
# 3. inheritance resolution (declared vs effective, origin)
# ===========================================================================
def test_inheritance_child_overrides_parent(tmp_path):
    child = json_family.parse_json(ORCA_CHILD, "child.json", "OrcaSlicer")
    parent = json_family.parse_json(ORCA_PARENT, "parent.json", "OrcaSlicer")
    repo = Repository.from_profiles([child, parent])
    resolved = inheritance.resolve(child, repo)
    # child value wins
    assert resolved.raw_fields["outer_wall_speed"].parsed_value == [120.0] or \
           resolved.raw_fields["outer_wall_speed"].parsed_value == ["120"]
    # inherited-only key present
    assert "layer_height" in resolved.raw_fields
    assert "layer_height" in resolved.inherited_keys
    assert "outer_wall_speed" in resolved.declared_keys
    assert resolved.origin_map["layer_height"] == "0.20mm Base"


def test_inheritance_missing_parent_warns():
    child = json_family.parse_json(ORCA_CHILD, "child.json", "OrcaSlicer")
    repo = Repository.from_profiles([child])   # parent absent
    resolved = inheritance.resolve(child, repo)
    assert any("親プリセット" in w for w in resolved.inheritance_warnings)


def test_inheritance_cycle_detected():
    a = json_family.parse_json(
        json.dumps({"type": "process", "name": "A", "inherits": "B", "k": "1"}),
        "a.json", "OrcaSlicer")
    b = json_family.parse_json(
        json.dumps({"type": "process", "name": "B", "inherits": "A", "k": "2"}),
        "b.json", "OrcaSlicer")
    repo = Repository.from_profiles([a, b])
    resolved = inheritance.resolve(a, repo)
    assert any("循環" in w for w in resolved.inheritance_warnings)


# ===========================================================================
# 4. native -> canonical (reverse registry) + unmapped preservation
# ===========================================================================
def test_reverse_index_is_one_to_one_only():
    idx = to_canonical.build_reverse_index("orca")
    assert idx["layer_height"][0] == "process.quality.layer_height"
    assert idx["outer_wall_speed"][0] == "process.speed.outer_wall"
    # one_to_many "line_width" must not be reversed
    assert "line_width" not in idx


def test_to_canonical_maps_and_preserves_unknown():
    prof = json_family.parse_json(ORCA_PARENT, "p.json", "OrcaSlicer")
    canonical = to_canonical.to_canonical(prof, "orca", "OrcaSlicer", "2.3")
    assert m.effective_of(canonical, "process.quality.layer_height") == 0.2
    assert m.effective_of(canonical, "process.strength.sparse_infill_density") == 15.0
    # configured layer, not observed
    node = m.get_value(canonical, "process.quality.layer_height")
    assert node["configured"] == 0.2
    assert node["observed"] is None
    # unknown key preserved
    assert "some_orca_only_key" in canonical["unmapped"]


def test_to_canonical_unit_conversion_reversed():
    prof = xml_family.parse_xml(S3D_FFF, "p.fff", "Simplify3D")
    canonical = to_canonical.to_canonical(prof, "simplify3d", "Simplify3D")
    # defaultSpeed 3600 mm/min -> 60 mm/s inner_wall
    assert m.effective_of(canonical, "process.speed.inner_wall") == 60.0


# ===========================================================================
# 5. public import_profile
# ===========================================================================
def test_import_profile_resolves_inheritance_from_siblings(tmp_path):
    _write(tmp_path, "parent.json", ORCA_PARENT)
    child_path = _write(tmp_path, "child.json", ORCA_CHILD)
    canonical = importers.import_profile(child_path)
    # inherited from sibling parent
    assert m.effective_of(canonical, "process.quality.layer_height") == 0.2
    # child override
    assert m.effective_of(canonical, "process.speed.outer_wall") == 120.0
    assert canonical["detection"]["slicer"] == "OrcaSlicer"


def test_import_profile_prusa(tmp_path):
    p = _write(tmp_path, "config.ini", PRUSA_INI)
    canonical = importers.import_profile(p)
    assert m.effective_of(canonical, "process.quality.layer_height") == 0.2
    assert m.effective_of(canonical, "process.strength.wall_loops") == 3
    assert m.effective_of(canonical, "process.speed.outer_wall") == 30.0
    assert "weird_prusa_key" in canonical["unmapped"]


def test_import_profile_unknown_slicer_raises(tmp_path):
    p = _write(tmp_path, "junk.txt", "nothing recognizable here")
    with pytest.raises(importers.ImportError_):
        importers.import_profile(p)


def test_import_from_archive(tmp_path):
    zp = os.path.join(str(tmp_path), "proj.3mf")
    with zipfile.ZipFile(zp, "w") as zf:
        zf.writestr("Metadata/project_settings.config", ORCA_PARENT)
        zf.writestr("Metadata/plate_1.gcode", "; G-code\nG1 X0\n")
    canonical = importers.import_profile(zp)
    assert m.effective_of(canonical, "process.quality.layer_height") == 0.2


# ===========================================================================
# 6. security
# ===========================================================================
def test_zip_path_traversal_rejected(tmp_path):
    zp = os.path.join(str(tmp_path), "evil.zip")
    with zipfile.ZipFile(zp, "w") as zf:
        zf.writestr("ok.json", ORCA_PARENT)
    # inject a traversal name directly
    with zipfile.ZipFile(zp, "a") as zf:
        zf.writestr("../escape.txt", "x")
    with zipfile.ZipFile(zp) as zf:
        with pytest.raises(security.UnsafeArchive):
            list(security.safe_zip_members(zf))


# ===========================================================================
# 7. merge configured + observed with conflict recording
# ===========================================================================
def _observed_result():
    return {
        "meta": {"source": "Unknown", "method": "ツールパス逆算"},
        "quality": {"layer_height": 0.2, "outer_wall_width": 0.42},
        "speed": {"outer_wall_speed": 95},     # differs from profile 120
        "strength": {"wall_loops": 3, "has_support": None, "has_raft": None},
        "temperature": {"nozzle_temp": 215},
        "retraction": {},
    }


def test_import_and_merge_records_conflict(tmp_path):
    _write(tmp_path, "parent.json", ORCA_PARENT)
    child_path = _write(tmp_path, "child.json", ORCA_CHILD)
    merged = importers.import_and_merge(child_path, _observed_result())

    node = m.get_value(merged, "process.speed.outer_wall")
    assert node["configured"] == 120.0
    assert node["observed"] == 95 or node["emitted"] == 95
    # conflict recorded
    conflict_keys = {c["canonical_key"] for c in merged["metadata"]["conflicts"]}
    assert "process.speed.outer_wall" in conflict_keys
    # effective prefers configured (profile) over observed
    assert node["effective"] == 120.0


def test_merge_agreeing_values_no_conflict(tmp_path):
    p = _write(tmp_path, "config.ini", PRUSA_INI)
    result = {
        "meta": {}, "quality": {"layer_height": 0.2},
        "speed": {}, "strength": {}, "temperature": {}, "retraction": {},
    }
    merged = importers.import_and_merge(p, result)
    node = m.get_value(merged, "process.quality.layer_height")
    assert node["configured"] == 0.2
    conflict_keys = {c["canonical_key"] for c in merged["metadata"]["conflicts"]}
    assert "process.quality.layer_height" not in conflict_keys


# ===========================================================================
# 8. no pairwise conversion / all through canonical
# ===========================================================================
def test_bambu_and_orca_use_separate_adapters():
    from gcode_profiler.importers import adapters
    assert adapters.for_slicer("OrcaSlicer").target == "orca"
    assert adapters.for_slicer("BambuStudio").target == "bambu"
    assert adapters.for_slicer("PrusaSlicer").target == "prusa"
    assert adapters.for_slicer("SuperSlicer").target == "superslicer"


# ===========================================================================
# 9. GUI model bridge (native import -> editable model -> canonical export)
# ===========================================================================
def test_gui_model_loads_imported_profile_as_configured(tmp_path):
    from gcode_profiler.gui import Model

    p = _write(tmp_path, "config.ini", PRUSA_INI)
    canonical = importers.import_profile(p)
    model = Model()
    model.load_canonical_profile(canonical)

    assert model.values["quality.layer_height"] == 0.2
    assert model.provenance["quality.layer_height"] == "imported_profile"
    assert model.values["speed.outer_wall_speed"] == 30.0
    assert model.meta["method"] == "プロファイル読込"
    assert model.meta["unmapped_count"] >= 1

    model.values["speed.outer_wall_speed"] = 44.0
    model.provenance["speed.outer_wall_speed"] = "edited"
    edited = model.to_canonical_profile()
    node = m.get_value(edited, "process.speed.outer_wall")
    assert node["configured"] == 30.0
    assert node["edited"] == 44.0
    assert node["effective"] == 44.0


def test_export_flow_accepts_imported_canonical_profile(tmp_path):
    from gcode_profiler import export_flow

    p = _write(tmp_path, "config.ini", PRUSA_INI)
    canonical = importers.import_profile(p)
    _prof, plan = export_flow.build_plan_from_canonical(canonical, "prusa")
    assert plan["target"] == "prusa"
    assert any(e["canonical_key"] == "process.quality.layer_height"
               and e["effective_value"] == 0.2
               for e in plan["entries"])
