# -*- coding: utf-8 -*-
"""Format / slicer / version / profile-kind detection (Phase 6).

Never identifies the slicer from extension alone; uses content signatures.
"""
from __future__ import annotations

import json
import os
import re


def _result(fmt=None, slicer="Unknown", version=None, kind="unknown",
            container="file", confidence=0.0, evidence=None, warnings=None):
    return {"format": fmt, "slicer": slicer, "version": version,
            "profile_kind": kind, "container_type": container,
            "confidence": round(confidence, 3), "evidence": evidence or [],
            "warnings": warnings or []}


def detect_text(text, ext=""):
    head = text.lstrip()[:4000]
    low = head.lower()
    ext = ext.lower()

    # JSON family (Orca / Bambu)
    if head.startswith("{"):
        try:
            obj = json.loads(text)
        except ValueError:
            obj = None
        if isinstance(obj, dict):
            kind = {"process": "process", "filament": "filament",
                    "machine": "printer"}.get(str(obj.get("type", "")).lower(), "unknown")
            ver = obj.get("version")
            keys = set(obj.keys())
            is_orcafam = bool(keys & {"from", "setting_id", "is_custom_defined",
                                      "inherits", "outer_wall_speed", "sparse_infill_density"})
            if is_orcafam:
                if "bambu" in low or "bbl" in low or any("bbl" in str(v).lower()
                                                         for v in obj.values() if isinstance(v, str)):
                    return _result("json", "BambuStudio", ver, kind, confidence=0.7,
                                   evidence=["JSON + Bambu signature"])
                return _result("json", "OrcaSlicer", ver, kind, confidence=0.75,
                               evidence=["JSON + Orca-family keys"])

    # Cura instance container (.cfg / .inst.cfg)
    if "[metadata]" in low and ("setting_version" in low or "quality_type" in low
                                or "[values]" in low):
        ver = _re1(r"setting_version\s*=\s*(\d+)", head)
        kind = "process" if "quality_changes" in low else "unknown"
        return _result("cfg", "Cura", ver, kind, confidence=0.7, evidence=["Cura [metadata]/[values]"])

    # Simplify3D FFF (XML)
    if head.startswith("<?xml") or "<profile" in low:
        if "<profile" in low and ("autoconfigure" in low or "fff" in ext or "<layerheight" in low):
            ver = _re1(r'version="([^"]+)"', head)
            return _result("xml", "Simplify3D", ver, "process", confidence=0.7,
                           evidence=["FFF <profile> XML"])

    # INI family (Prusa / SuperSlicer / config bundle)
    if "=" in head and re.search(r"^\s*[\w]+\s*=", head, re.M):
        bundle = bool(re.search(r"^\s*\[(print|filament|printer)[:\]]", head, re.M | re.I))
        slicer = "PrusaSlicer"
        if "superslicer" in low or "_ss_" in low or "support_material_interface_speed" in low:
            slicer = "SuperSlicer"
        elif "generated by superslicer" in low:
            slicer = "SuperSlicer"
        # signature keys
        if re.search(r"external_perimeter_speed|perimeters\s*=|fill_density", head):
            ver = _re1(r"generated by \w+ ([\d.]+)", head)
            return _result("ini", slicer, ver,
                           "bundle" if bundle else "process",
                           "bundle" if bundle else "file", 0.65,
                           evidence=["INI key=value + Prusa-family keys"])

    return _result(confidence=0.0, warnings=["未判定フォーマット"])


def detect(path):
    ext = os.path.splitext(path)[1]
    with open(path, "r", encoding="utf-8", errors="replace") as f:
        text = f.read()
    res = detect_text(text, ext)
    res["_text"] = text  # cached for the importer (avoid re-read)
    return res


def _re1(pattern, text, flags=re.I):
    m = re.search(pattern, text, flags)
    return m.group(1) if m else None
