# -*- coding: utf-8 -*-
"""
設定項目スキーマ (OrcaSlicer のプリンター/フィラメント/プロセス設定画面を踏襲)
=============================================================================
各設定グループ(printer/filament/process)を「サブタブ → セクション → フィールド」で定義。
G-code から復元可能な項目は src(解析結果パス)を持ち、自動でプリフィルされる。

Field.visibility     : "basic" | "advanced" | "expert"
Field.recoverability : "explicit"|"runtime"|"geometry"|"estimated"|"profile_only"|"target_only"
Field.native_key     : OrcaSlicer 等の確認済みネイティブキー (None = 未確認)
Field.canonical_key  : Phase 6 向け標準キー ("" = 未設定)
"""
from __future__ import annotations

from dataclasses import dataclass, field as dc_field
from typing import Optional


@dataclass
class Field:
    key: str                            # 値ストアの一意キー ("section.field" 形式)
    label: str
    unit: str = ""
    kind: str = "num"                   # num | int | bool | text | choice | color | gcode
    choices: Optional[list] = None
    default: object = None
    src: Optional[str] = None           # 解析結果からのプリフィル元 "sec.field"
    low_conf: bool = False
    # --- Phase 5.5 拡張メタデータ ---
    native_key: Optional[str] = None    # 確認済みネイティブキー (OrcaSlicer 等)
    canonical_key: str = ""             # Phase 6 標準キー
    description: str = ""              # ツールチップ用説明
    visibility: str = "basic"           # basic | advanced | expert
    per_tool: bool = False              # ツール別に独立した値を持つか
    enabled_if: list = dc_field(default_factory=list)   # 依存フィールドキーのリスト
    visible_if: list = dc_field(default_factory=list)   # 表示条件フィールドキーのリスト
    recoverability: str = "profile_only"  # G-codeからの回復方法
    deprecated: bool = False


@dataclass
class SubTab:
    title: str
    sections: list = dc_field(default_factory=list)  # [(section_title, [Field,...]), ...]
    special: Optional[str] = None   # None / "filaments" / "gcode" / "per_filament"


# ---------------------------------------------------------------------------
# エイリアス: 旧キー → canonical_key (Phase 6 向けドキュメント・マイグレーション用)
# 実行時には適用されない。既存 Field.key は変更せず維持。
# ---------------------------------------------------------------------------
ALIASES: dict[str, str] = {
    "quality.outer_wall_width":    "process.quality.line_width.outer_wall",
    "quality.inner_wall_width":    "process.quality.line_width.inner_wall",
    "quality.sparse_infill_width": "process.quality.line_width.sparse_infill",
    "quality.top_surface_width":   "process.quality.line_width.top_surface",
    "quality.support_width":       "process.quality.line_width.support",
    "speed.outer_wall_speed":      "process.speed.outer_wall",
    "speed.inner_wall_speed":      "process.speed.inner_wall",
    "speed.sparse_infill_speed":   "process.speed.sparse_infill",
    "speed.top_surface_speed":     "process.speed.top_surface",
    "speed.travel_speed":          "process.speed.travel",
    "speed.first_layer_speed":     "process.speed.first_layer",
    "speed.support_speed":         "process.speed.support",
    "speed.outer_wall_accel":      "process.speed.accel.outer_wall",
    "strength.has_support":        "process.support.setting_enabled_state",
    "strength.has_raft":           "process.raft.setting_enabled_state",
    "quality.skirt_brim_line_width": "process.quality.line_width.skirt",
    "quality.skirt_line_width":    "process.quality.line_width.skirt",
    "quality.brim_line_width":     "process.quality.line_width.brim",
    "quality.raft_line_width":     "process.quality.line_width.raft",
    "machine.printable_area":      "printer.basic_information.bed_shape",
    "machine.printable_height":    "printer.basic_information.printable_height",
    "support.path_present":        "process.support.path_present",
    "support.setting_enabled_state": "process.support.setting_enabled_state",
    "raft.path_present":           "process.raft.path_present",
    "raft.setting_enabled_state":   "process.raft.setting_enabled_state",
}


# ===========================================================================
# プロセス設定
# ===========================================================================
PROCESS = [
    # -----------------------------------------------------------------------
    SubTab("品質", [
        ("積層", [
            Field("quality.layer_height", "積層ピッチ", "mm",
                  src="quality.layer_height",
                  native_key="layer_height",
                  canonical_key="process.quality.layer_height",
                  recoverability="geometry"),
            Field("quality.first_layer_height", "最初の層の高さ", "mm",
                  src="quality.first_layer_height",
                  native_key="initial_layer_print_height",
                  canonical_key="process.quality.first_layer_height",
                  recoverability="geometry"),
            Field("quality.variable_layer_height", "可変積層ピッチ", kind="bool",
                  default=False,
                  native_key="enable_overhang_speed",      # 未確認
                  canonical_key="process.quality.variable_layer_height",
                  recoverability="profile_only",
                  visibility="advanced",
                  description="Z 方向のオーバーハングに応じて積層ピッチを自動調整"),
            Field("quality.adaptive_layer_max_gradient", "最大勾配", "mm",
                  default=0.2,
                  canonical_key="process.quality.adaptive_layer_max_gradient",
                  recoverability="profile_only",
                  visibility="advanced",
                  enabled_if=["quality.variable_layer_height"],
                  description="可変積層ピッチの最大段差"),
        ]),
        ("ライン幅", [
            Field("quality.default_line_width", "デフォルトライン幅", "mm",
                  native_key="line_width",
                  canonical_key="process.quality.line_width.default",
                  recoverability="profile_only",
                  description="指定されていない場合のデフォルトライン幅"),
            Field("quality.first_layer_line_width", "最初の層のライン幅", "mm",
                  native_key="initial_layer_line_width",
                  canonical_key="process.quality.line_width.first_layer",
                  recoverability="profile_only"),
            Field("quality.outer_wall_width", "外壁", "mm",
                  src="quality.outer_wall_width",
                  native_key="outer_wall_line_width",
                  canonical_key="process.quality.line_width.outer_wall",
                  recoverability="geometry"),
            Field("quality.inner_wall_width", "内壁", "mm",
                  src="quality.inner_wall_width",
                  native_key="inner_wall_line_width",
                  canonical_key="process.quality.line_width.inner_wall",
                  recoverability="geometry"),
            Field("quality.top_surface_width", "上面", "mm",
                  src="quality.top_surface_width",
                  native_key="top_surface_line_width",
                  canonical_key="process.quality.line_width.top_surface",
                  recoverability="geometry"),
            Field("quality.bottom_surface_line_width", "底面", "mm",
                  native_key="bottom_surface_line_width",
                  canonical_key="process.quality.line_width.bottom_surface",
                  recoverability="profile_only"),
            Field("quality.internal_solid_infill_line_width", "内部ソリッドインフィル", "mm",
                  native_key="internal_solid_infill_line_width",
                  canonical_key="process.quality.line_width.internal_solid_infill",
                  recoverability="profile_only"),
            Field("quality.sparse_infill_width", "インフィル", "mm",
                  src="quality.sparse_infill_width",
                  native_key="sparse_infill_line_width",
                  canonical_key="process.quality.line_width.sparse_infill",
                  recoverability="geometry"),
            Field("quality.support_width", "サポート", "mm",
                  src="quality.support_width",
                  native_key="support_line_width",
                  canonical_key="process.quality.line_width.support",
                  recoverability="geometry"),
            Field("quality.support_interface_line_width", "サポートインターフェース", "mm",
                  native_key="support_interface_line_width",
                  canonical_key="process.quality.line_width.support_interface",
                  recoverability="profile_only"),
            Field("quality.bridge_line_width", "ブリッジ", "mm",
                  src="quality.bridge_width",
                  native_key="bridge_line_width",
                  canonical_key="process.quality.line_width.bridge",
                  recoverability="geometry"),
            Field("quality.gap_fill_line_width", "ギャップフィル", "mm",
                  native_key="gap_infill_speed",          # 未確認
                  canonical_key="process.quality.line_width.gap_fill",
                  recoverability="profile_only",
                  visibility="advanced"),
            Field("quality.skirt_brim_line_width", "スカート/ブリム", "mm",
                  native_key="skirt_line_width",
                  canonical_key="process.quality.line_width.skirt_brim",
                  recoverability="profile_only",
                  visibility="expert",
                  deprecated=True,
                  description="旧互換キー。新規編集ではスカート/ブリムを個別に設定"),
            Field("quality.skirt_line_width", "スカート", "mm",
                  native_key="skirt_line_width",
                  canonical_key="process.quality.line_width.skirt",
                  recoverability="profile_only",
                  visibility="advanced"),
            Field("quality.brim_line_width", "ブリム", "mm",
                  canonical_key="process.quality.line_width.brim",
                  recoverability="profile_only",
                  visibility="advanced",
                  description="OrcaSlicer native_key は未確認"),
            Field("quality.raft_line_width", "ラフト", "mm",
                  canonical_key="process.quality.line_width.raft",
                  recoverability="profile_only",
                  visibility="advanced",
                  description="OrcaSlicer native_key は未確認"),
        ]),
        ("シーム", [
            Field("quality.seam_position", "シーム位置", kind="choice",
                  choices=["nearest", "aligned", "back", "random"],
                  default="aligned",
                  native_key="seam_position",
                  canonical_key="process.quality.seam.position",
                  recoverability="profile_only"),
            Field("quality.seam_gap", "シームギャップ", "mm",
                  default=0.0,
                  native_key="seam_gap",
                  canonical_key="process.quality.seam.gap",
                  recoverability="profile_only",
                  visibility="advanced"),
            Field("quality.scarf_seam_enabled", "スカーフシーム", kind="bool",
                  default=False,
                  native_key="scarf_seam_enabled",        # 未確認
                  canonical_key="process.quality.seam.scarf",
                  recoverability="profile_only",
                  visibility="advanced"),
            Field("quality.seam_painting", "シームペイント状態", kind="choice",
                  choices=["unknown", "painted", "not_painted"],
                  default="unknown",
                  canonical_key="process.quality.seam.painting_state",
                  recoverability="profile_only",
                  visibility="advanced",
                  description="OrcaSlicer native_key は未確認"),
            Field("quality.staggered_inner_seams", "内壁シームをずらす", kind="bool",
                  default=False,
                  native_key="staggered_inner_seam",      # 未確認
                  canonical_key="process.quality.seam.staggered_inner",
                  recoverability="profile_only",
                  visibility="advanced"),
        ]),
        ("精度", [
            Field("quality.resolution", "解像度", "mm",
                  default=0.0,
                  native_key="resolution",
                  canonical_key="process.quality.precision.resolution",
                  recoverability="profile_only",
                  visibility="advanced",
                  description="0 = 無効化。小さいほど精密（処理時間増加）"),
            Field("quality.arc_fitting_enabled", "弧フィッティング", kind="bool",
                  default=False,
                  native_key="enable_arc_fitting",
                  canonical_key="process.quality.precision.arc_fitting",
                  recoverability="profile_only",
                  visibility="advanced"),
            Field("quality.xy_compensation", "XY 補正", "mm",
                  default=0.0,
                  native_key="xy_hole_compensation",      # 未確認
                  canonical_key="process.quality.precision.xy_compensation",
                  recoverability="profile_only",
                  visibility="advanced"),
            Field("quality.elephant_foot_compensation", "エレファントフット補正", "mm",
                  default=0.0,
                  native_key="elefant_foot_compensation", # 未確認
                  canonical_key="process.quality.precision.elephant_foot_compensation",
                  recoverability="profile_only",
                  visibility="advanced"),
            Field("quality.slice_gap_closing_radius", "スライスギャップ閉合半径", "mm",
                  default=0.05,
                  native_key="slice_closing_radius",      # 未確認
                  canonical_key="process.quality.precision.slice_gap_closing_radius",
                  recoverability="profile_only",
                  visibility="expert"),
        ]),
    ]),
    # -----------------------------------------------------------------------
    SubTab("強度", [
        ("ウォール", [
            Field("strength.wall_loops", "ウォールのループ数", "本", kind="int",
                  src="strength.wall_loops", low_conf=True,
                  native_key="wall_loops",
                  canonical_key="process.strength.wall_loops",
                  recoverability="estimated"),
            Field("strength.wall_generator", "ウォールジェネレーター", kind="choice",
                  choices=["Classic", "Arachne"],
                  default="Classic",
                  native_key="wall_generator",
                  canonical_key="process.strength.wall_generator",
                  recoverability="profile_only",
                  visibility="advanced"),
            Field("strength.wall_printing_order", "印刷順序", kind="choice",
                  choices=["inner wall first", "outer wall first"],
                  default="inner wall first",
                  native_key="wall_sequence",
                  canonical_key="process.strength.wall_printing_order",
                  recoverability="profile_only",
                  visibility="advanced"),
            Field("strength.print_infill_first", "インフィルを先に印刷", kind="bool",
                  default=False,
                  native_key="infill_first",
                  canonical_key="process.strength.print_infill_first",
                  recoverability="profile_only",
                  visibility="advanced"),
            Field("strength.detect_thin_walls", "細い壁を検出", kind="bool",
                  default=True,
                  native_key="detect_thin_wall",
                  canonical_key="process.strength.detect_thin_walls",
                  recoverability="profile_only",
                  visibility="advanced"),
            Field("strength.minimum_wall_width", "最小ウォール幅", "mm",
                  default=0.0,
                  native_key="min_width_top_open_poly",   # 未確認
                  canonical_key="process.strength.minimum_wall_width",
                  recoverability="profile_only",
                  visibility="advanced"),
            Field("strength.minimum_feature_size", "最小フィーチャーサイズ", "mm",
                  default=0.0,
                  native_key="minimum_feature_size",
                  canonical_key="process.strength.minimum_feature_size",
                  recoverability="profile_only",
                  visibility="expert"),
            Field("strength.wall_overlap", "ウォールオーバーラップ", "%",
                  default=15.0,
                  native_key="wall_infill_gap",            # 未確認
                  canonical_key="process.strength.wall_overlap",
                  recoverability="profile_only",
                  visibility="advanced"),
            Field("strength.inner_outer_wall_overlap", "内壁/外壁オーバーラップ", "%",
                  default=10.0,
                  canonical_key="process.strength.inner_outer_wall_overlap",
                  recoverability="profile_only",
                  visibility="expert"),
            Field("strength.gap_fill_enabled", "ギャップフィルを有効化", kind="bool",
                  default=True,
                  native_key="gap_fill_enabled",           # 未確認
                  canonical_key="process.strength.gap_fill_enabled",
                  recoverability="profile_only"),
        ]),
        ("上面と底面", [
            Field("strength.top_shell_layers", "上面シェル層数", "層", kind="int",
                  default=4,
                  native_key="top_shell_layers",
                  canonical_key="process.strength.top_shell_layers",
                  recoverability="profile_only"),
            Field("strength.bottom_shell_layers", "底面シェル層数", "層", kind="int",
                  default=4,
                  native_key="bottom_shell_layers",
                  canonical_key="process.strength.bottom_shell_layers",
                  recoverability="profile_only"),
            Field("strength.top_shell_thickness", "上面シェル厚さ", "mm",
                  default=0.0,
                  native_key="top_shell_thickness",
                  canonical_key="process.strength.top_shell_thickness",
                  recoverability="profile_only"),
            Field("strength.bottom_shell_thickness", "底面シェル厚さ", "mm",
                  default=0.0,
                  native_key="bottom_shell_thickness",
                  canonical_key="process.strength.bottom_shell_thickness",
                  recoverability="profile_only"),
            Field("strength.top_surface_pattern", "上面パターン", kind="choice",
                  choices=["monotonic", "monotonicline", "concentric", "zig-zag", "rectilinear"],
                  default="monotonic",
                  native_key="top_surface_pattern",
                  canonical_key="process.strength.top_surface_pattern",
                  recoverability="profile_only"),
            Field("strength.bottom_surface_pattern", "底面パターン", kind="choice",
                  choices=["monotonic", "monotonicline", "concentric", "zig-zag", "rectilinear"],
                  default="monotonic",
                  native_key="bottom_surface_pattern",
                  canonical_key="process.strength.bottom_surface_pattern",
                  recoverability="profile_only"),
            Field("strength.internal_solid_infill_pattern", "内部ソリッドパターン", kind="choice",
                  choices=["auto", "rectilinear", "monotonic", "concentric", "zig-zag"],
                  default="auto",
                  native_key="internal_solid_infill_pattern",
                  canonical_key="process.strength.internal_solid_infill_pattern",
                  recoverability="profile_only"),
            Field("strength.monotonic_top_surface", "モノトニック上面", kind="bool",
                  default=True,
                  canonical_key="process.strength.monotonic_top_surface",
                  recoverability="profile_only",
                  visibility="advanced"),
            Field("strength.ironing_enabled", "アイロニングを有効化", kind="bool",
                  default=False,
                  native_key="ironing",
                  canonical_key="process.strength.ironing_enabled",
                  recoverability="profile_only"),
            Field("strength.ironing_type", "アイロニングタイプ", kind="choice",
                  choices=["top", "topmost", "solid"],
                  default="top",
                  native_key="ironing_type",
                  canonical_key="process.strength.ironing_type",
                  recoverability="profile_only",
                  visibility="advanced",
                  enabled_if=["strength.ironing_enabled"]),
            Field("strength.ironing_flow", "アイロニングフロー", "%",
                  default=15.0,
                  native_key="ironing_flow",
                  canonical_key="process.strength.ironing_flow",
                  recoverability="profile_only",
                  visibility="advanced",
                  enabled_if=["strength.ironing_enabled"]),
            Field("strength.ironing_spacing", "アイロニング間隔", "mm",
                  default=0.1,
                  native_key="ironing_spacing",
                  canonical_key="process.strength.ironing_spacing",
                  recoverability="profile_only",
                  visibility="advanced",
                  enabled_if=["strength.ironing_enabled"]),
            Field("strength.ironing_speed", "アイロニング速度", "mm/s",
                  default=20.0,
                  native_key="ironing_speed",
                  canonical_key="process.strength.ironing_speed",
                  recoverability="profile_only",
                  visibility="advanced",
                  enabled_if=["strength.ironing_enabled"]),
        ]),
        ("インフィル", [
            Field("strength.sparse_infill_density_pct", "インフィル密度", "%",
                  src="strength.sparse_infill_density_pct", low_conf=True,
                  native_key="sparse_infill_density",
                  canonical_key="process.strength.sparse_infill_density",
                  recoverability="estimated"),
            Field("strength.sparse_infill_pattern", "インフィルパターン", kind="choice",
                  choices=["grid", "honeycomb", "gyroid", "rectilinear", "line",
                           "cubic", "triangles", "tri-hexagon", "cross",
                           "cross-3d", "adaptive_cubic", "support_cubic",
                           "lightning", "concentric"],
                  default="grid",
                  native_key="sparse_infill_pattern",
                  canonical_key="process.strength.sparse_infill_pattern",
                  recoverability="profile_only"),
            Field("strength.infill_direction", "インフィル方向", "°",
                  default=45.0,
                  native_key="infill_direction",
                  canonical_key="process.strength.infill_direction",
                  recoverability="profile_only",
                  visibility="advanced"),
            Field("strength.solid_infill_direction", "ソリッドインフィル方向", "°",
                  default=45.0,
                  native_key="solid_infill_direction",     # 未確認
                  canonical_key="process.strength.solid_infill_direction",
                  recoverability="profile_only",
                  visibility="advanced"),
            Field("strength.infill_combination", "インフィル結合", kind="bool",
                  default=False,
                  native_key="infill_combination",
                  canonical_key="process.strength.infill_combination",
                  recoverability="profile_only",
                  visibility="advanced"),
            Field("strength.infill_anchor", "インフィルアンカー長さ", "mm",
                  default=2.5,
                  native_key="infill_anchor",
                  canonical_key="process.strength.infill_anchor",
                  recoverability="profile_only",
                  visibility="advanced"),
            Field("strength.infill_anchor_max", "インフィルアンカー最大長", "mm",
                  default=12.0,
                  native_key="infill_anchor_max",
                  canonical_key="process.strength.infill_anchor_max",
                  recoverability="profile_only",
                  visibility="advanced"),
            Field("strength.infill_wall_overlap", "インフィル/ウォールオーバーラップ", "%",
                  default=15.0,
                  native_key="infill_wall_intersection",
                  canonical_key="process.strength.infill_wall_overlap",
                  recoverability="profile_only",
                  visibility="advanced"),
            Field("strength.min_sparse_infill_area", "最小スパースインフィル面積", "mm²",
                  default=15.0,
                  native_key="minimum_sparse_infill_area",
                  canonical_key="process.strength.min_sparse_infill_area",
                  recoverability="profile_only",
                  visibility="advanced"),
        ]),
    ]),
    # -----------------------------------------------------------------------
    SubTab("速度", [
        ("外壁/内壁", [
            Field("speed.outer_wall_speed", "外壁", "mm/s",
                  src="speed.outer_wall_speed",
                  native_key="outer_wall_speed",
                  canonical_key="process.speed.outer_wall",
                  recoverability="geometry"),
            Field("speed.inner_wall_speed", "内壁", "mm/s",
                  src="speed.inner_wall_speed",
                  native_key="inner_wall_speed",
                  canonical_key="process.speed.inner_wall",
                  recoverability="geometry"),
            Field("speed.small_perimeter_speed", "小さな外周", "mm/s",
                  default=25.0,
                  native_key="small_perimeter_speed",
                  canonical_key="process.speed.small_perimeter",
                  recoverability="profile_only"),
        ]),
        ("インフィル/上面", [
            Field("speed.sparse_infill_speed", "インフィル", "mm/s",
                  src="speed.sparse_infill_speed",
                  native_key="sparse_infill_speed",
                  canonical_key="process.speed.sparse_infill",
                  recoverability="geometry"),
            Field("speed.top_surface_speed", "上面", "mm/s",
                  src="speed.top_surface_speed",
                  native_key="top_surface_speed",
                  canonical_key="process.speed.top_surface",
                  recoverability="geometry"),
            Field("speed.internal_solid_infill_speed", "内部ソリッドインフィル", "mm/s",
                  default=200.0,
                  native_key="internal_solid_infill_speed",
                  canonical_key="process.speed.internal_solid_infill",
                  recoverability="profile_only"),
            Field("speed.first_layer_infill_speed", "最初の層のインフィル", "mm/s",
                  default=30.0,
                  native_key="initial_layer_infill_speed",
                  canonical_key="process.speed.first_layer_infill",
                  recoverability="profile_only"),
        ]),
        ("ブリッジ/オーバーハング", [
            Field("speed.bridge_speed", "ブリッジ", "mm/s",
                  default=50.0,
                  native_key="bridge_speed",
                  canonical_key="process.speed.bridge",
                  recoverability="profile_only"),
            Field("speed.internal_bridge_speed", "内部ブリッジ", "mm/s",
                  default=150.0,
                  native_key="internal_bridge_speed",
                  canonical_key="process.speed.internal_bridge",
                  recoverability="profile_only"),
            Field("speed.overhang_speed_0", "オーバーハング速度 (0-25%)", "mm/s",
                  default=60.0,
                  native_key="overhang_1_4_speed",        # 未確認
                  canonical_key="process.speed.overhang_0_25",
                  recoverability="profile_only",
                  visibility="advanced"),
            Field("speed.overhang_speed_1", "オーバーハング速度 (25-50%)", "mm/s",
                  default=40.0,
                  native_key="overhang_2_4_speed",        # 未確認
                  canonical_key="process.speed.overhang_25_50",
                  recoverability="profile_only",
                  visibility="advanced"),
            Field("speed.overhang_speed_2", "オーバーハング速度 (50-75%)", "mm/s",
                  default=20.0,
                  native_key="overhang_3_4_speed",        # 未確認
                  canonical_key="process.speed.overhang_50_75",
                  recoverability="profile_only",
                  visibility="advanced"),
            Field("speed.overhang_speed_3", "オーバーハング速度 (75-100%)", "mm/s",
                  default=10.0,
                  canonical_key="process.speed.overhang_75_100",
                  recoverability="profile_only",
                  visibility="advanced",
                  description="OrcaSlicer native_key は未確認"),
            Field("speed.gap_fill_speed", "ギャップフィル", "mm/s",
                  default=30.0,
                  native_key="gap_infill_speed",
                  canonical_key="process.speed.gap_fill",
                  recoverability="profile_only",
                  visibility="advanced"),
        ]),
        ("移動/サポート", [
            Field("speed.travel_speed", "移動速度", "mm/s",
                  src="speed.travel_speed",
                  native_key="travel_speed",
                  canonical_key="process.speed.travel",
                  recoverability="explicit"),
            Field("speed.first_layer_speed", "最初の層", "mm/s",
                  src="speed.first_layer_speed",
                  native_key="initial_layer_speed",
                  canonical_key="process.speed.first_layer",
                  recoverability="geometry"),
            Field("speed.support_speed", "サポート", "mm/s",
                  src="speed.support_speed",
                  native_key="support_speed",
                  canonical_key="process.speed.support",
                  recoverability="geometry"),
            Field("speed.support_interface_speed", "サポートインターフェース", "mm/s",
                  default=80.0,
                  native_key="support_interface_speed",
                  canonical_key="process.speed.support_interface",
                  recoverability="profile_only"),
        ]),
        ("加速度", [
            Field("speed.outer_wall_accel", "外壁加速度", "mm/s²",
                  src="speed.outer_wall_accel",
                  native_key="outer_wall_acceleration",
                  canonical_key="process.speed.accel.outer_wall",
                  recoverability="explicit"),
            Field("speed.inner_wall_accel", "内壁加速度", "mm/s²",
                  default=0.0,
                  native_key="inner_wall_acceleration",
                  canonical_key="process.speed.accel.inner_wall",
                  recoverability="profile_only"),
            Field("speed.top_surface_accel", "上面加速度", "mm/s²",
                  default=0.0,
                  native_key="top_surface_acceleration",
                  canonical_key="process.speed.accel.top_surface",
                  recoverability="profile_only"),
            Field("speed.sparse_infill_accel", "インフィル加速度", "mm/s²",
                  default=0.0,
                  native_key="sparse_infill_acceleration",
                  canonical_key="process.speed.accel.sparse_infill",
                  recoverability="profile_only"),
            Field("speed.travel_accel", "移動加速度", "mm/s²",
                  default=0.0,
                  native_key="travel_acceleration",
                  canonical_key="process.speed.accel.travel",
                  recoverability="profile_only"),
            Field("speed.first_layer_accel", "最初の層加速度", "mm/s²",
                  default=0.0,
                  native_key="initial_layer_acceleration",
                  canonical_key="process.speed.accel.first_layer",
                  recoverability="profile_only"),
            Field("speed.bridge_accel", "ブリッジ加速度", "mm/s²",
                  default=0.0,
                  native_key="bridge_acceleration",
                  canonical_key="process.speed.accel.bridge",
                  recoverability="profile_only"),
        ]),
        ("ジャーク", [
            Field("speed.outer_wall_jerk", "外壁ジャーク", "mm/s",
                  default=0.0,
                  canonical_key="process.speed.jerk.outer_wall",
                  recoverability="profile_only",
                  visibility="expert",
                  description="OrcaSlicer native_key は未確認"),
            Field("speed.inner_wall_jerk", "内壁ジャーク", "mm/s",
                  default=0.0,
                  canonical_key="process.speed.jerk.inner_wall",
                  recoverability="profile_only",
                  visibility="expert",
                  description="OrcaSlicer native_key は未確認"),
            Field("speed.sparse_infill_jerk", "インフィルジャーク", "mm/s",
                  default=0.0,
                  canonical_key="process.speed.jerk.sparse_infill",
                  recoverability="profile_only",
                  visibility="expert",
                  description="OrcaSlicer native_key は未確認"),
            Field("speed.travel_jerk", "移動ジャーク", "mm/s",
                  default=0.0,
                  canonical_key="process.speed.jerk.travel",
                  recoverability="profile_only",
                  visibility="expert",
                  description="OrcaSlicer native_key は未確認"),
        ]),
    ]),
    # -----------------------------------------------------------------------
    SubTab("サポート", [
        ("サポート", [
            Field("strength.has_support", "サポート材を有効化", kind="bool",
                  native_key="enable_support",
                  canonical_key="process.support.setting_enabled_state",
                  recoverability="profile_only",
                  deprecated=True,
                  visibility="expert",
                  description="旧互換キー。新規表示では support.setting_enabled_state を使用"),
            Field("support.setting_enabled_state", "サポート設定状態", kind="choice",
                  choices=["unknown", "enabled", "disabled"],
                  default="unknown",
                  native_key="enable_support",
                  canonical_key="process.support.setting_enabled_state",
                  recoverability="profile_only",
                  description="プロファイル上のサポート有効状態。G-code経路の有無とは別"),
            Field("support.path_present", "サポート経路あり", kind="bool",
                  src="strength.has_support",
                  canonical_key="process.support.path_present",
                  recoverability="geometry",
                  visibility="advanced",
                  description="G-code上で観測されたサポート経路の有無"),
            Field("support.support_type", "サポートタイプ", kind="choice",
                  choices=["normal(auto)", "tree(auto)", "normal(manual)", "tree(manual)"],
                  default="normal(auto)",
                  native_key="support_type",
                  canonical_key="process.support.type",
                  recoverability="profile_only",
                  enabled_if=["support.setting_enabled_state"]),
            Field("support.support_style", "サポートスタイル", kind="choice",
                  choices=["default", "grid", "snug"],
                  default="default",
                  native_key="support_style",
                  canonical_key="process.support.style",
                  recoverability="profile_only",
                  enabled_if=["support.setting_enabled_state"]),
            Field("support.threshold_angle", "サポートしきい値角度", "°",
                  default=30.0,
                  native_key="support_threshold_angle",
                  canonical_key="process.support.threshold_angle",
                  recoverability="profile_only",
                  enabled_if=["support.setting_enabled_state"]),
            Field("support.on_build_plate_only", "ビルドプレートのみ", kind="bool",
                  default=False,
                  native_key="support_on_build_plate_only",
                  canonical_key="process.support.on_build_plate_only",
                  recoverability="profile_only",
                  enabled_if=["support.setting_enabled_state"]),
            Field("support.critical_regions_only", "重要領域のみ", kind="bool",
                  default=False,
                  native_key="support_critical_regions_only", # 未確認
                  canonical_key="process.support.critical_regions_only",
                  recoverability="profile_only",
                  visibility="advanced"),
            Field("support.support_pattern", "サポートパターン", kind="choice",
                  choices=["rectilinear", "rectilinear-grid", "honeycomb",
                           "lightning", "default"],
                  default="rectilinear",
                  native_key="support_base_pattern",
                  canonical_key="process.support.pattern",
                  recoverability="profile_only"),
            Field("support.support_spacing", "サポート間隔", "mm",
                  default=2.5,
                  native_key="support_base_pattern_spacing",
                  canonical_key="process.support.spacing",
                  recoverability="profile_only"),
            Field("support.support_expansion", "サポート拡大", "mm",
                  default=0.0,
                  native_key="support_expansion",
                  canonical_key="process.support.expansion",
                  recoverability="profile_only",
                  visibility="advanced"),
            Field("support.support_xy_distance", "サポートXY距離", "mm",
                  default=0.35,
                  native_key="support_object_xy_distance",
                  canonical_key="process.support.xy_distance",
                  recoverability="profile_only"),
            Field("support.top_z_distance", "上面Z距離", "mm",
                  default=0.2,
                  native_key="support_top_z_distance",
                  canonical_key="process.support.top_z_distance",
                  recoverability="profile_only"),
            Field("support.bottom_z_distance", "底面Z距離", "mm",
                  default=0.0,
                  native_key="support_bottom_z_distance",
                  canonical_key="process.support.bottom_z_distance",
                  recoverability="profile_only"),
            Field("support.interface_enabled", "サポートインターフェース", kind="bool",
                  default=True,
                  native_key="enable_support_interface",
                  canonical_key="process.support.interface_enabled",
                  recoverability="profile_only"),
            Field("support.top_interface_layers", "上面インターフェース層数", "層", kind="int",
                  default=2,
                  native_key="support_interface_top_layers",
                  canonical_key="process.support.top_interface_layers",
                  recoverability="profile_only",
                  enabled_if=["support.interface_enabled"]),
            Field("support.bottom_interface_layers", "底面インターフェース層数", "層", kind="int",
                  default=0,
                  native_key="support_interface_bottom_layers",
                  canonical_key="process.support.bottom_interface_layers",
                  recoverability="profile_only",
                  enabled_if=["support.interface_enabled"]),
            Field("support.interface_pattern", "インターフェースパターン", kind="choice",
                  choices=["auto", "rectilinear", "concentric", "rectilinear_interlaced",
                           "grid"],
                  default="auto",
                  native_key="support_interface_pattern",
                  canonical_key="process.support.interface_pattern",
                  recoverability="profile_only",
                  visibility="advanced",
                  enabled_if=["support.interface_enabled"]),
            Field("support.interface_spacing", "インターフェース間隔", "mm",
                  default=0.5,
                  native_key="support_interface_spacing",
                  canonical_key="process.support.interface_spacing",
                  recoverability="profile_only",
                  visibility="advanced",
                  enabled_if=["support.interface_enabled"]),
            Field("support.independent_layer_height", "独立サポート積層ピッチ", kind="bool",
                  default=False,
                  native_key="independent_support_layer_height",
                  canonical_key="process.support.independent_layer_height",
                  recoverability="profile_only",
                  visibility="advanced"),
            Field("support.tree_branch_diameter", "ツリーブランチ径", "mm",
                  default=5.0,
                  native_key="tree_support_branch_diameter",
                  canonical_key="process.support.tree_branch_diameter",
                  recoverability="profile_only",
                  visibility="advanced"),
            Field("support.tree_branch_angle", "ツリーブランチ角度", "°",
                  default=40.0,
                  native_key="tree_support_branch_angle",
                  canonical_key="process.support.tree_branch_angle",
                  recoverability="profile_only",
                  visibility="advanced"),
            Field("support.tree_tip_diameter", "ツリー先端径", "mm",
                  default=0.8,
                  native_key="tree_support_tip_diameter",
                  canonical_key="process.support.tree_tip_diameter",
                  recoverability="profile_only",
                  visibility="expert"),
            Field("support.tree_wall_count", "ツリーウォール数", "本", kind="int",
                  default=1,
                  native_key="tree_support_wall_count",
                  canonical_key="process.support.tree_wall_count",
                  recoverability="profile_only",
                  visibility="expert"),
        ]),
        ("ラフト", [
            Field("strength.has_raft", "ラフトを有効化", kind="bool",
                  canonical_key="process.raft.setting_enabled_state",
                  recoverability="profile_only",
                  deprecated=True,
                  visibility="expert",
                  description="旧互換キー。新規表示では raft.setting_enabled_state を使用"),
            Field("raft.setting_enabled_state", "ラフト設定状態", kind="choice",
                  choices=["unknown", "enabled", "disabled"],
                  default="unknown",
                  canonical_key="process.raft.setting_enabled_state",
                  recoverability="profile_only",
                  description="プロファイル上のラフト有効状態。G-code経路の有無とは別"),
            Field("raft.path_present", "ラフト経路あり", kind="bool",
                  src="strength.has_raft",
                  canonical_key="process.raft.path_present",
                  recoverability="geometry",
                  visibility="advanced",
                  description="G-code上で観測されたラフト/負レイヤ経路の有無"),
            Field("raft.raft_layers", "ラフト層数", "層", kind="int",
                  default=2,
                  native_key="raft_layers",
                  canonical_key="process.raft.layers",
                  recoverability="profile_only",
                  enabled_if=["raft.setting_enabled_state"]),
            Field("raft.raft_contact_distance", "ラフト接触距離", "mm",
                  default=0.1,
                  native_key="raft_contact_distance",
                  canonical_key="process.raft.contact_distance",
                  recoverability="profile_only",
                  enabled_if=["raft.setting_enabled_state"]),
            Field("raft.raft_expansion", "ラフト拡大", "mm",
                  default=1.5,
                  native_key="raft_expansion",
                  canonical_key="process.raft.expansion",
                  recoverability="profile_only",
                  enabled_if=["raft.setting_enabled_state"]),
            Field("raft.raft_first_layer_density", "ラフト最初の層密度", "%",
                  default=90.0,
                  native_key="raft_first_layer_density",
                  canonical_key="process.raft.first_layer_density",
                  recoverability="profile_only",
                  visibility="advanced",
                  enabled_if=["raft.setting_enabled_state"]),
            Field("raft.raft_first_layer_line_width", "ラフト最初の層幅", "mm",
                  default=0.8,
                  native_key="raft_first_layer_line_width",
                  canonical_key="process.raft.first_layer_line_width",
                  recoverability="profile_only",
                  visibility="advanced",
                  enabled_if=["raft.setting_enabled_state"]),
            Field("raft.raft_interface_spacing", "ラフトインターフェース間隔", "mm",
                  default=0.3,
                  native_key="raft_interface_spacing",
                  canonical_key="process.raft.interface_spacing",
                  recoverability="profile_only",
                  visibility="advanced",
                  enabled_if=["raft.setting_enabled_state"]),
        ]),
    ]),
    # -----------------------------------------------------------------------
    SubTab("その他", [
        ("リトラクション", [
            Field("retraction.retract_length", "リトラクト長", "mm",
                  src="retraction.retract_length",
                  native_key="retract_length",
                  canonical_key="process.retraction.retract_length",
                  recoverability="explicit"),
            Field("retraction.retract_speed", "リトラクト速度", "mm/s",
                  src="retraction.retract_speed",
                  native_key="retract_speed",
                  canonical_key="process.retraction.retract_speed",
                  recoverability="explicit"),
            Field("retraction.deretract_speed", "戻し速度", "mm/s",
                  src="retraction.deretract_speed",
                  native_key="deretract_speed",
                  canonical_key="process.retraction.deretract_speed",
                  recoverability="explicit"),
            Field("retraction.z_hop_height", "Zホップ高さ", "mm",
                  src="retraction.z_hop_height",
                  native_key="z_hop",
                  canonical_key="process.retraction.z_hop_height",
                  recoverability="explicit"),
        ]),
        ("床面接着", [
            Field("others.skirt_loops", "スカートループ数", "本", kind="int",
                  default=1,
                  native_key="skirt_loops",
                  canonical_key="process.others.skirt_loops",
                  recoverability="profile_only"),
            Field("others.skirt_distance", "スカート距離", "mm",
                  default=2.0,
                  native_key="skirt_distance",
                  canonical_key="process.others.skirt_distance",
                  recoverability="profile_only"),
            Field("others.skirt_height", "スカート高さ", "層", kind="int",
                  default=1,
                  native_key="skirt_height",
                  canonical_key="process.others.skirt_height",
                  recoverability="profile_only",
                  visibility="advanced"),
            Field("others.draft_shield_enabled", "ドラフトシールド", kind="bool",
                  default=False,
                  native_key="draft_shield",
                  canonical_key="process.others.draft_shield",
                  recoverability="profile_only",
                  visibility="expert"),
            Field("others.brim_type", "ブリムタイプ", kind="choice",
                  choices=["no_brim", "outer_only", "inner_only", "outer_and_inner",
                           "auto_brim"],
                  default="no_brim",
                  native_key="brim_type",
                  canonical_key="process.others.brim_type",
                  recoverability="profile_only"),
            Field("others.brim_width", "ブリム幅", "mm",
                  default=5.0,
                  native_key="brim_width",
                  canonical_key="process.others.brim_width",
                  recoverability="profile_only",
                  enabled_if=["others.brim_type"]),
            Field("others.brim_object_gap", "ブリム/オブジェクト隙間", "mm",
                  default=0.0,
                  native_key="brim_object_gap",
                  canonical_key="process.others.brim_object_gap",
                  recoverability="profile_only",
                  visibility="advanced",
                  enabled_if=["others.brim_type"]),
            Field("others.mouse_ear_enabled", "マウスイヤー", kind="bool",
                  default=False,
                  native_key="mouse_ear_detection",       # 未確認
                  canonical_key="process.others.mouse_ear",
                  recoverability="profile_only",
                  visibility="advanced"),
        ]),
        ("特殊モード", [
            Field("others.spiral_vase", "スパイラル花瓶モード", kind="bool",
                  default=False,
                  native_key="spiral_mode",
                  canonical_key="process.others.spiral_vase",
                  recoverability="profile_only"),
            Field("others.fuzzy_skin_enabled", "ファジースキン", kind="bool",
                  default=False,
                  native_key="fuzzy_skin",
                  canonical_key="process.others.fuzzy_skin",
                  recoverability="profile_only",
                  visibility="advanced"),
            Field("others.fuzzy_skin_thickness", "ファジースキン厚さ", "mm",
                  default=0.3,
                  native_key="fuzzy_skin_thickness",
                  canonical_key="process.others.fuzzy_skin_thickness",
                  recoverability="profile_only",
                  visibility="advanced",
                  enabled_if=["others.fuzzy_skin_enabled"]),
            Field("others.fuzzy_skin_point_distance", "ファジースキン点間距離", "mm",
                  default=0.8,
                  native_key="fuzzy_skin_point_dist",
                  canonical_key="process.others.fuzzy_skin_point_distance",
                  recoverability="profile_only",
                  visibility="advanced",
                  enabled_if=["others.fuzzy_skin_enabled"]),
            Field("others.only_one_wall_on_top", "上面は1壁のみ", kind="bool",
                  default=False,
                  native_key="only_one_wall_top",
                  canonical_key="process.others.only_one_wall_on_top",
                  recoverability="profile_only",
                  visibility="advanced"),
            Field("others.only_one_wall_on_first", "最初の層は1壁のみ", kind="bool",
                  default=False,
                  native_key="only_one_wall_first_layer", # 未確認
                  canonical_key="process.others.only_one_wall_on_first",
                  recoverability="profile_only",
                  visibility="advanced"),
            Field("others.sequential_printing", "順次印刷", kind="bool",
                  default=False,
                  native_key="print_sequence",
                  canonical_key="process.others.sequential_printing",
                  recoverability="profile_only",
                  visibility="advanced"),
            Field("others.sequential_object_order", "オブジェクト順序", kind="choice",
                  choices=["auto", "shortest_path"],
                  default="auto",
                  canonical_key="process.others.sequential_object_order",
                  recoverability="profile_only",
                  visibility="advanced",
                  enabled_if=["others.sequential_printing"]),
            Field("others.timelapse_mode", "タイムラプスモード", kind="choice",
                  choices=["none", "smooth", "traditional"],
                  default="none",
                  native_key="timelapse_type",
                  canonical_key="process.others.timelapse_mode",
                  recoverability="profile_only",
                  visibility="advanced"),
            Field("others.exclude_objects", "オブジェクト除外を有効化", kind="bool",
                  default=False,
                  native_key="exclude_object",
                  canonical_key="process.others.exclude_objects",
                  recoverability="profile_only",
                  visibility="advanced"),
            Field("others.adaptive_pressure_advance", "アダプティブ PA", kind="bool",
                  default=False,
                  native_key="enable_pressure_advance",   # 未確認
                  canonical_key="process.others.adaptive_pressure_advance",
                  recoverability="profile_only",
                  visibility="expert"),
        ]),
    ]),
    # -----------------------------------------------------------------------
    SubTab("Multimaterial", [
        ("ワイプタワー", [
            Field("mm.wipe_tower_enabled", "ワイプタワーを有効化", kind="bool",
                  default=False,
                  native_key="enable_prime_tower",
                  canonical_key="process.mm.wipe_tower_enabled",
                  recoverability="profile_only"),
            Field("mm.wipe_tower_x", "ワイプタワー X 位置", "mm",
                  default=180.0,
                  native_key="wipe_tower_x",
                  canonical_key="process.mm.wipe_tower_x",
                  recoverability="profile_only",
                  enabled_if=["mm.wipe_tower_enabled"]),
            Field("mm.wipe_tower_y", "ワイプタワー Y 位置", "mm",
                  default=140.0,
                  native_key="wipe_tower_y",
                  canonical_key="process.mm.wipe_tower_y",
                  recoverability="profile_only",
                  enabled_if=["mm.wipe_tower_enabled"]),
            Field("mm.wipe_tower_width", "ワイプタワー幅", "mm",
                  default=60.0,
                  native_key="prime_tower_width",
                  canonical_key="process.mm.wipe_tower_width",
                  recoverability="profile_only",
                  enabled_if=["mm.wipe_tower_enabled"]),
            Field("mm.wipe_tower_rotation", "ワイプタワー回転角", "°",
                  default=0.0,
                  native_key="wipe_tower_rotation_angle",
                  canonical_key="process.mm.wipe_tower_rotation",
                  recoverability="profile_only",
                  visibility="advanced",
                  enabled_if=["mm.wipe_tower_enabled"]),
            Field("mm.purge_volumes", "パージ量", "", kind="text",
                  default="",
                  canonical_key="process.mm.purge_volumes",
                  recoverability="profile_only",
                  visibility="advanced",
                  description="ツール間パージ量行列。OrcaSlicer native_key は未確認"),
            Field("mm.flush_into_infill", "インフィルへフラッシュ", kind="bool",
                  default=False,
                  native_key="flush_into_infill",
                  canonical_key="process.mm.flush_into_infill",
                  recoverability="profile_only"),
            Field("mm.flush_into_support", "サポートへフラッシュ", kind="bool",
                  default=False,
                  native_key="flush_into_support",
                  canonical_key="process.mm.flush_into_support",
                  recoverability="profile_only"),
            Field("mm.flush_into_objects", "オブジェクトへフラッシュ", kind="bool",
                  default=False,
                  native_key="flush_into_objects",
                  canonical_key="process.mm.flush_into_objects",
                  recoverability="profile_only"),
            Field("mm.prime_tower_brim", "プライムタワーブリム", kind="bool",
                  default=False,
                  native_key="prime_tower_brim_width",    # 未確認(bool vs width)
                  canonical_key="process.mm.prime_tower_brim",
                  recoverability="profile_only",
                  visibility="advanced"),
            Field("mm.wall_tool", "ウォール用ツール", "", kind="text",
                  default="",
                  canonical_key="process.mm.tool_assignment.wall",
                  recoverability="profile_only",
                  visibility="advanced",
                  description="OrcaSlicer native_key は未確認"),
            Field("mm.infill_tool", "インフィル用ツール", "", kind="text",
                  default="",
                  canonical_key="process.mm.tool_assignment.infill",
                  recoverability="profile_only",
                  visibility="advanced",
                  description="OrcaSlicer native_key は未確認"),
            Field("mm.support_tool", "サポート用ツール", "", kind="text",
                  default="",
                  canonical_key="process.mm.tool_assignment.support",
                  recoverability="profile_only",
                  visibility="advanced",
                  description="OrcaSlicer native_key は未確認"),
        ]),
    ]),
    # -----------------------------------------------------------------------
    SubTab("G-code", [
        ("プロセス G-code", [
            Field("gcode.before_layer_change_gcode", "before layer change G-code", kind="gcode",
                  default="",
                  canonical_key="process.gcode.before_layer_change",
                  recoverability="profile_only",
                  visibility="advanced"),
            Field("gcode.process_layer_change_gcode", "layer change G-code", kind="gcode",
                  default="",
                  canonical_key="process.gcode.layer_change",
                  recoverability="profile_only",
                  visibility="advanced"),
            Field("gcode.process_toolchange_gcode", "toolchange G-code", kind="gcode",
                  default="",
                  canonical_key="process.gcode.toolchange",
                  recoverability="profile_only",
                  visibility="advanced"),
            Field("gcode.process_pause_gcode", "pause G-code", kind="gcode",
                  default="",
                  canonical_key="process.gcode.pause",
                  recoverability="profile_only",
                  visibility="advanced"),
            Field("gcode.process_custom_gcode", "custom process G-code", kind="gcode",
                  default="",
                  canonical_key="process.gcode.custom",
                  recoverability="profile_only",
                  visibility="expert"),
        ]),
    ]),
]


# ===========================================================================
# プリンター設定
# ===========================================================================
PRINTER = [
    SubTab("基本情報", [
        ("造形可能領域", [
            Field("machine.printable_area", "造形可能領域", "", kind="text",
                  default="0x0,250x0,250x250,0x250",
                  native_key="printable_area",
                  canonical_key="printer.basic_information.bed_shape",
                  recoverability="profile_only"),
            Field("machine.bed_exclude_area", "除外領域", "", kind="text",
                  default="",
                  native_key="bed_exclude_area",
                  canonical_key="printer.bed_exclude_area",
                  recoverability="profile_only"),
            Field("machine.printable_height", "造形可能高さ", "mm",
                  src="meta.z_max",
                  native_key="printable_height",
                  canonical_key="printer.basic_information.printable_height",
                  recoverability="geometry"),
            Field("machine.printable_origin", "造形原点", "", kind="text",
                  default="0,0",
                  native_key="printable_origin",
                  canonical_key="printer.printable_origin",
                  recoverability="profile_only",
                  visibility="advanced"),
        ]),
        ("高度な設定", [
            Field("machine.printer_structure", "Printer structure", "", kind="choice",
                  choices=["CoreXY", "i3", "Delta", "Hangprinter", "MarkForged"],
                  default="CoreXY",
                  native_key="printer_structure",
                  canonical_key="printer.printer_structure",
                  recoverability="profile_only"),
            Field("machine.gcode_flavor", "G-codeスタイル", "", kind="choice",
                  choices=["Marlin(legacy)", "Marlin(firmware retract)", "Klipper",
                           "RepRap/Sprinter", "RepRapFirmware", "Smoothieware", "産業機(独自)"],
                  default="Marlin(legacy)",
                  native_key="gcode_flavor",
                  canonical_key="printer.gcode_flavor",
                  recoverability="profile_only"),
            Field("machine.inspect_first_layer", "1層目を検査", kind="bool",
                  default=True,
                  canonical_key="printer.inspect_first_layer",
                  recoverability="profile_only",
                  visibility="advanced"),
        ]),
        ("押出機", [
            Field("machine.nozzle_diameter", "ノズル径(推定)", "mm",
                  src="meta.nozzle_diameter_est", low_conf=True,
                  native_key="nozzle_diameter",
                  canonical_key="printer.nozzle_diameter",
                  recoverability="estimated"),
            Field("machine.nozzle_volume", "内腔容積", "mm³",
                  default=0,
                  native_key="nozzle_volume",
                  canonical_key="printer.nozzle_volume",
                  recoverability="profile_only",
                  visibility="advanced"),
            Field("machine.extruder_count", "エクストルーダー数", "本", kind="int",
                  default=1,
                  native_key="extruder_count",
                  canonical_key="printer.extruder_count",
                  recoverability="profile_only"),
            Field("machine.extruder_offsets", "エクストルーダーオフセット", "", kind="text",
                  default="0,0",
                  native_key="extruder_offset",
                  canonical_key="printer.extruder_offsets",
                  recoverability="profile_only",
                  visibility="advanced",
                  description="各エクストルーダーの XY オフセット (例: 0x0, 20x0)"),
            Field("machine.filament_diameter", "フィラメント径", "mm",
                  default=1.75,
                  native_key="filament_diameter",          # 未確認(機械側)
                  canonical_key="printer.filament_diameter",
                  recoverability="profile_only"),
            Field("machine.single_extruder_mm_enabled", "シングル押出マルチマテリアル", kind="bool",
                  default=False,
                  native_key="single_extruder_multi_material",
                  canonical_key="printer.single_extruder_mm",
                  recoverability="profile_only",
                  visibility="advanced"),
            Field("machine.z_offset", "Zオフセット", "mm",
                  default=0,
                  canonical_key="printer.z_offset",
                  recoverability="profile_only",
                  visibility="advanced"),
        ]),
        ("冷却ファン", [
            Field("machine.fan_speedup_time", "Fan speed-up time", "s",
                  default=0,
                  native_key="fan_speedup_time",
                  canonical_key="printer.fan_speedup_time",
                  recoverability="profile_only",
                  visibility="expert"),
            Field("machine.fan_kickstart_time", "Fan kick-start time", "s",
                  default=0,
                  native_key="fan_kickstart_time",
                  canonical_key="printer.fan_kickstart_time",
                  recoverability="profile_only",
                  visibility="expert"),
        ]),
        ("押出機クリアランス", [
            Field("machine.clearance_radius", "半径", "mm",
                  default=45,
                  native_key="extruder_clearance_radius",
                  canonical_key="printer.clearance_radius",
                  recoverability="profile_only",
                  visibility="advanced"),
            Field("machine.height_to_rod", "レールまでの高さ", "mm",
                  default=40,
                  native_key="extruder_clearance_height_to_rod",
                  canonical_key="printer.height_to_rod",
                  recoverability="profile_only",
                  visibility="advanced"),
            Field("machine.height_to_lid", "蓋までの高さ", "mm",
                  default=120,
                  native_key="extruder_clearance_height_to_lid",
                  canonical_key="printer.height_to_lid",
                  recoverability="profile_only",
                  visibility="advanced"),
        ]),
    ]),
    # -----------------------------------------------------------------------
    SubTab("エクストルーダー", [
        ("リトラクション", [
            Field("machine.retract_length", "リトラクト長", "mm",
                  default=0.5,
                  native_key="retract_length",
                  canonical_key="printer.extruder.retract_length",
                  recoverability="profile_only",
                  description="プリンターデフォルトのリトラクト長 (プロセス値で上書き可)"),
            Field("machine.retract_speed", "リトラクト速度", "mm/s",
                  default=45.0,
                  native_key="retract_speed",
                  canonical_key="printer.extruder.retract_speed",
                  recoverability="profile_only"),
            Field("machine.deretract_speed", "戻し速度", "mm/s",
                  default=0.0,
                  native_key="deretract_speed",
                  canonical_key="printer.extruder.deretract_speed",
                  recoverability="profile_only",
                  description="0 = リトラクト速度と同じ"),
            Field("machine.retract_before_wipe", "ワイプ前リトラクト", "%",
                  default=0.0,
                  native_key="retract_before_wipe",
                  canonical_key="printer.extruder.retract_before_wipe",
                  recoverability="profile_only",
                  visibility="advanced"),
            Field("machine.retract_on_layer_change", "層変更でリトラクト", kind="bool",
                  default=False,
                  native_key="retract_layer_change",
                  canonical_key="printer.extruder.retract_on_layer_change",
                  recoverability="profile_only",
                  visibility="advanced"),
            Field("machine.extra_restart_length", "リスタート余長", "mm",
                  default=0.0,
                  native_key="retract_restart_extra",
                  canonical_key="printer.extruder.extra_restart_length",
                  recoverability="profile_only",
                  visibility="advanced"),
        ]),
        ("ワイプ", [
            Field("machine.wipe_while_retracting", "リトラクション時にワイプ", kind="bool",
                  default=False,
                  native_key="wipe",
                  canonical_key="printer.extruder.wipe_while_retracting",
                  recoverability="profile_only"),
            Field("machine.wipe_distance", "ワイプ距離", "mm",
                  default=1.5,
                  native_key="wipe_distance",
                  canonical_key="printer.extruder.wipe_distance",
                  recoverability="profile_only",
                  enabled_if=["machine.wipe_while_retracting"]),
        ]),
        ("Zホップ", [
            Field("machine.z_hop_height", "Zホップ高さ", "mm",
                  default=0.0,
                  native_key="z_hop",
                  canonical_key="printer.extruder.z_hop_height",
                  recoverability="profile_only"),
            Field("machine.z_hop_type", "Zホップタイプ", kind="choice",
                  choices=["normal", "slope", "spiral"],
                  default="normal",
                  native_key="z_hop_types",
                  canonical_key="printer.extruder.z_hop_type",
                  recoverability="profile_only",
                  visibility="advanced",
                  enabled_if=["machine.z_hop_height"]),
            Field("machine.min_travel_after_retract", "リトラクト後最小移動距離", "mm",
                  default=1.0,
                  native_key="retract_min_travel",
                  canonical_key="printer.extruder.min_travel_after_retract",
                  recoverability="profile_only",
                  visibility="advanced"),
            Field("machine.travel_slope", "移動傾斜", kind="bool",
                  default=False,
                  canonical_key="printer.extruder.travel_slope",
                  recoverability="profile_only",
                  visibility="expert"),
        ]),
        ("ツールチェンジ", [
            Field("machine.toolchange_retract_length", "ツールチェンジ リトラクト長", "mm",
                  default=10.0,
                  native_key="retract_length_toolchange",
                  canonical_key="printer.extruder.toolchange_retract_length",
                  recoverability="profile_only",
                  visibility="advanced"),
            Field("machine.toolchange_restart_extra", "ツールチェンジ リスタート余長", "mm",
                  default=0.0,
                  native_key="retract_restart_extra_toolchange",
                  canonical_key="printer.extruder.toolchange_restart_extra",
                  recoverability="profile_only",
                  visibility="advanced"),
        ]),
    ]),
    # -----------------------------------------------------------------------
    SubTab("移動能力", [
        # NOTE: Machine motion limits must come from explicit M201/M203/M205/M566/
        # SET_VELOCITY_LIMIT only. Process acceleration and travel speed must NOT
        # populate these printer-capability fields.
        ("最大加速度", [
            Field("machine.max_accel_x", "X", "mm/s²",
                  src="machine.max_accel_x",
                  native_key="machine_max_acceleration_x",
                  canonical_key="printer.limits.max_accel_x",
                  recoverability="explicit"),
            Field("machine.max_accel_y", "Y", "mm/s²",
                  src="machine.max_accel_y",
                  native_key="machine_max_acceleration_y",
                  canonical_key="printer.limits.max_accel_y",
                  recoverability="explicit"),
            Field("machine.max_accel_z", "Z", "mm/s²",
                  src="machine.max_accel_z",
                  native_key="machine_max_acceleration_z",
                  canonical_key="printer.limits.max_accel_z",
                  recoverability="explicit"),
            Field("machine.max_accel_e", "E", "mm/s²",
                  src="machine.max_accel_e",
                  native_key="machine_max_acceleration_e",
                  canonical_key="printer.limits.max_accel_e",
                  recoverability="explicit"),
        ]),
        ("最大速度", [
            Field("machine.max_speed_x", "X", "mm/s",
                  src="machine.max_speed_x",
                  native_key="machine_max_speed_x",
                  canonical_key="printer.limits.max_speed_x",
                  recoverability="explicit"),
            Field("machine.max_speed_y", "Y", "mm/s",
                  src="machine.max_speed_y",
                  native_key="machine_max_speed_y",
                  canonical_key="printer.limits.max_speed_y",
                  recoverability="explicit"),
            Field("machine.max_speed_z", "Z", "mm/s",
                  src="machine.max_speed_z",
                  native_key="machine_max_speed_z",
                  canonical_key="printer.limits.max_speed_z",
                  recoverability="explicit"),
            Field("machine.max_speed_e", "E", "mm/s",
                  src="machine.max_speed_e",
                  native_key="machine_max_speed_e",
                  canonical_key="printer.limits.max_speed_e",
                  recoverability="explicit"),
        ]),
        ("ジャーク", [
            Field("machine.max_jerk_x", "X", "mm/s",
                  src="machine.max_jerk_x",
                  native_key="machine_max_jerk_x",
                  canonical_key="printer.limits.max_jerk_x",
                  recoverability="explicit",
                  visibility="advanced"),
            Field("machine.max_jerk_y", "Y", "mm/s",
                  src="machine.max_jerk_y",
                  native_key="machine_max_jerk_y",
                  canonical_key="printer.limits.max_jerk_y",
                  recoverability="explicit",
                  visibility="advanced"),
            Field("machine.max_jerk_z", "Z", "mm/s",
                  src="machine.max_jerk_z",
                  native_key="machine_max_jerk_z",
                  canonical_key="printer.limits.max_jerk_z",
                  recoverability="explicit",
                  visibility="advanced"),
            Field("machine.max_jerk_e", "E", "mm/s",
                  src="machine.max_jerk_e",
                  native_key="machine_max_jerk_e",
                  canonical_key="printer.limits.max_jerk_e",
                  recoverability="explicit",
                  visibility="advanced"),
        ]),
        ("加速度上書き", [
            Field("machine.max_accel_for_extrusion", "押出し時", "mm/s²",
                  default=0.0,
                  native_key="machine_max_acceleration_extruding",
                  canonical_key="printer.limits.max_accel_for_extrusion",
                  recoverability="explicit",
                  visibility="advanced",
                  description="M204 E — 押出し時加速度上限"),
            Field("machine.max_accel_for_retraction", "リトラクション時", "mm/s²",
                  default=0.0,
                  native_key="machine_max_acceleration_retracting",
                  canonical_key="printer.limits.max_accel_for_retraction",
                  recoverability="explicit",
                  visibility="advanced"),
            Field("machine.max_accel_for_travel", "移動時", "mm/s²",
                  default=0.0,
                  native_key="machine_max_acceleration_travel",
                  canonical_key="printer.limits.max_accel_for_travel",
                  recoverability="explicit",
                  visibility="advanced"),
        ]),
        ("最小速度", [
            Field("machine.min_feed_rate", "最小送り速度", "mm/s",
                  default=0.0,
                  native_key="machine_min_extruding_rate", # 未確認
                  canonical_key="printer.limits.min_feed_rate",
                  recoverability="explicit",
                  visibility="expert"),
            Field("machine.min_travel_feed_rate", "最小移動速度", "mm/s",
                  default=0.0,
                  native_key="machine_min_travel_rate",    # 未確認
                  canonical_key="printer.limits.min_travel_feed_rate",
                  recoverability="explicit",
                  visibility="expert"),
        ]),
    ]),
    # -----------------------------------------------------------------------
    SubTab("Multimaterial", [
        ("ツール", [
            Field("machine.mm.tool_count", "ツール数", "本", kind="int",
                  default=1,
                  native_key="extruder_count",
                  canonical_key="printer.mm.tool_count",
                  recoverability="profile_only"),
            Field("machine.mm.tool_offsets", "ツールオフセット", "", kind="text",
                  default="0,0",
                  native_key="extruder_offset",
                  canonical_key="printer.mm.tool_offsets",
                  recoverability="profile_only",
                  visibility="advanced"),
            Field("machine.mm.purge_volume", "パージ量", "mm³",
                  default=0.0,
                  canonical_key="printer.mm.purge_volume",
                  recoverability="profile_only",
                  visibility="advanced",
                  description="OrcaSlicer native_key は未確認"),
            Field("machine.mm.wipe_tower_capable", "ワイプタワー対応", kind="bool",
                  default=False,
                  canonical_key="printer.mm.wipe_tower_capable",
                  recoverability="profile_only",
                  visibility="advanced",
                  description="OrcaSlicer native_key は未確認"),
        ]),
        ("フィラメント交換", [
            Field("machine.mm.filament_change_gcode", "フィラメント交換 G-code", kind="gcode",
                  default="",
                  canonical_key="printer.mm.filament_change_gcode",
                  recoverability="profile_only",
                  visibility="advanced",
                  description="OrcaSlicer native_key は未確認"),
            Field("machine.mm.toolchange_gcode", "ツールチェンジ G-code", kind="gcode",
                  default="",
                  canonical_key="printer.mm.toolchange_gcode",
                  recoverability="profile_only",
                  visibility="advanced",
                  description="OrcaSlicer native_key は未確認"),
            Field("machine.mm.parking_position", "パーキング位置", "", kind="text",
                  default="",
                  canonical_key="printer.mm.parking_position",
                  recoverability="profile_only",
                  visibility="advanced",
                  description="例: X,Y。OrcaSlicer native_key は未確認"),
            Field("machine.mm.cooling_tube_position", "冷却チューブ位置", "mm",
                  default=0.0,
                  canonical_key="printer.mm.cooling_tube_position",
                  recoverability="profile_only",
                  visibility="expert",
                  description="OrcaSlicer native_key は未確認"),
            Field("machine.mm.cooling_tube_length", "冷却チューブ長", "mm",
                  default=0.0,
                  canonical_key="printer.mm.cooling_tube_length",
                  recoverability="profile_only",
                  visibility="expert",
                  description="OrcaSlicer native_key は未確認"),
            Field("machine.mm.high_current_on_filament_swap", "フィラメント交換時高電流", kind="bool",
                  default=False,
                  canonical_key="printer.mm.high_current_on_filament_swap",
                  recoverability="profile_only",
                  visibility="expert",
                  description="OrcaSlicer native_key は未確認"),
        ]),
    ]),
    SubTab("ツール一覧", special="filaments"),
    SubTab("G-code", [
        ("プリンター G-code", [
            Field("gcode.machine_start_gcode", "machine start G-code", kind="gcode",
                  default="",
                  canonical_key="printer.gcode.machine_start",
                  recoverability="profile_only"),
            Field("gcode.machine_end_gcode", "machine end G-code", kind="gcode",
                  default="",
                  canonical_key="printer.gcode.machine_end",
                  recoverability="profile_only"),
            Field("gcode.layer_change_gcode", "layer change G-code", kind="gcode",
                  default="",
                  canonical_key="printer.gcode.layer_change",
                  recoverability="profile_only",
                  visibility="advanced"),
            Field("gcode.timelapse_gcode", "time-lapse G-code", kind="gcode",
                  default="",
                  canonical_key="printer.gcode.timelapse",
                  recoverability="profile_only",
                  visibility="advanced"),
            Field("gcode.toolchange_gcode", "toolchange G-code", kind="gcode",
                  default="",
                  canonical_key="printer.gcode.toolchange",
                  recoverability="profile_only",
                  visibility="advanced"),
            Field("gcode.pause_gcode", "pause G-code", kind="gcode",
                  default="",
                  canonical_key="printer.gcode.pause",
                  recoverability="profile_only",
                  visibility="advanced"),
            Field("gcode.template_custom_gcode", "template custom G-code", kind="gcode",
                  default="",
                  canonical_key="printer.gcode.template_custom",
                  recoverability="profile_only",
                  visibility="expert"),
        ]),
    ]),
    SubTab("Notes", [
        ("メモ", [
            Field("machine.notes", "Notes", "", kind="text",
                  default="",
                  canonical_key="printer.notes",
                  recoverability="profile_only"),
        ]),
    ]),
]


# ===========================================================================
# フィラメント設定
# ===========================================================================
FILAMENT = [
    SubTab("基本情報", [
        ("フィラメント", [
            Field("filament.type", "フィラメントタイプ", kind="choice",
                  choices=["PLA", "PETG", "ABS", "ASA", "TPU", "PA", "PA-CF",
                           "PC", "PLA-CF", "PETG-CF", "PVA", "PPS", "PPS-CF",
                           "PEEK", "PEKK", "PEI", "OTHER"],
                  default="PLA",
                  native_key="filament_type",
                  canonical_key="filament.type",
                  recoverability="profile_only"),
            Field("filament.vendor", "メーカー", kind="text",
                  default="",
                  native_key="filament_vendor",
                  canonical_key="filament.vendor",
                  recoverability="profile_only"),
            Field("filament.density", "密度", "g/cm³",
                  default=1.24,
                  native_key="filament_density",
                  canonical_key="filament.density",
                  recoverability="profile_only",
                  visibility="advanced"),
            Field("filament.diameter", "フィラメント径", "mm",
                  default=1.75,
                  native_key="filament_diameter",
                  canonical_key="filament.diameter",
                  recoverability="profile_only"),
            Field("filament.cost", "コスト", "円/kg",
                  default=0.0,
                  native_key="filament_cost",
                  canonical_key="filament.cost",
                  recoverability="profile_only",
                  visibility="advanced"),
            Field("filament.color", "カラー", kind="color",
                  default="#FFFFFF",
                  native_key="filament_colour",
                  canonical_key="filament.color",
                  recoverability="profile_only"),
            Field("filament.spool_weight", "スプール重量", "g",
                  default=1000.0,
                  native_key="filament_spool_weight",
                  canonical_key="filament.spool_weight",
                  recoverability="profile_only",
                  visibility="advanced"),
            Field("filament.flow_ratio", "フロー比", "",
                  default=1.0,
                  native_key="filament_flow_ratio",
                  canonical_key="filament.flow_ratio",
                  recoverability="profile_only"),
            Field("filament.max_volumetric_speed", "最大体積流量", "mm³/s",
                  default=0.0,
                  native_key="filament_max_volumetric_speed",
                  canonical_key="filament.max_volumetric_speed",
                  recoverability="profile_only",
                  description="0 = 無制限"),
            Field("filament.shrinkage", "収縮率", "%",
                  default=0.0,
                  native_key="filament_shrink",            # 未確認
                  canonical_key="filament.shrinkage",
                  recoverability="profile_only",
                  visibility="advanced"),
            Field("filament.softening_temperature", "軟化温度", "°C",
                  default=0.0,
                  native_key="temperature_vicat_softening",# 未確認
                  canonical_key="filament.softening_temperature",
                  recoverability="profile_only",
                  visibility="advanced"),
        ]),
    ]),
    # -----------------------------------------------------------------------
    SubTab("温度", [
        ("温度", [
            Field("filament.nozzle_temp_initial_layer", "ノズル温度 (最初の層)", "°C",
                  src="temperature.nozzle_temp",
                  native_key="nozzle_temperature_initial_layer",
                  canonical_key="filament.nozzle_temp_initial_layer",
                  recoverability="explicit",
                  per_tool=True),
            Field("filament.nozzle_temp", "ノズル温度 (その他の層)", "°C",
                  src="temperature.nozzle_temp",
                  native_key="nozzle_temperature",
                  canonical_key="filament.nozzle_temp",
                  recoverability="explicit",
                  per_tool=True),
            Field("filament.bed_temp_initial_layer", "ベッド温度 (最初の層)", "°C",
                  src="temperature.bed_temp",
                  native_key="bed_temperature_initial_layer",
                  canonical_key="filament.bed_temp_initial_layer",
                  recoverability="explicit",
                  per_tool=True),
            Field("filament.bed_temp", "ベッド温度 (その他の層)", "°C",
                  src="temperature.bed_temp",
                  native_key="bed_temperature",
                  canonical_key="filament.bed_temp",
                  recoverability="explicit",
                  per_tool=True),
            Field("filament.bed_temp_textured_plate", "Textured PEI Plate 温度", "°C",
                  default=None,
                  canonical_key="filament.bed_temp.textured_plate",
                  recoverability="profile_only",
                  visibility="advanced",
                  per_tool=True,
                  description="OrcaSlicer native_key は未確認"),
            Field("filament.bed_temp_smooth_plate", "Smooth PEI Plate 温度", "°C",
                  default=None,
                  canonical_key="filament.bed_temp.smooth_plate",
                  recoverability="profile_only",
                  visibility="advanced",
                  per_tool=True,
                  description="OrcaSlicer native_key は未確認"),
            Field("filament.bed_temp_engineering_plate", "Engineering Plate 温度", "°C",
                  default=None,
                  canonical_key="filament.bed_temp.engineering_plate",
                  recoverability="profile_only",
                  visibility="advanced",
                  per_tool=True,
                  description="OrcaSlicer native_key は未確認"),
            Field("filament.bed_temp_cool_plate", "Cool Plate 温度", "°C",
                  default=None,
                  canonical_key="filament.bed_temp.cool_plate",
                  recoverability="profile_only",
                  visibility="advanced",
                  per_tool=True,
                  description="OrcaSlicer native_key は未確認"),
            Field("filament.chamber_temp", "チャンバー温度", "°C",
                  src="temperature.chamber_temp",
                  native_key="chamber_temperature",
                  canonical_key="filament.chamber_temp",
                  recoverability="explicit"),
            Field("filament.min_print_temperature", "最低印刷温度", "°C",
                  default=0.0,
                  native_key="filament_min_extrude_temp",  # 未確認
                  canonical_key="filament.min_print_temperature",
                  recoverability="profile_only",
                  visibility="advanced"),
            Field("filament.max_print_temperature", "最高印刷温度", "°C",
                  default=0.0,
                  native_key="filament_max_temp",          # 未確認
                  canonical_key="filament.max_print_temperature",
                  recoverability="profile_only",
                  visibility="advanced"),
        ]),
    ]),
    # -----------------------------------------------------------------------
    SubTab("冷却", [
        ("ファン", [
            Field("temperature.fan_max_pct", "最大ファン速度", "%",
                  src="temperature.fan_max_pct",
                  native_key="fan_max_speed",
                  canonical_key="filament.fan_max_speed",
                  recoverability="explicit"),
            Field("filament.fan_min_speed", "最小ファン速度", "%",
                  default=20.0,
                  native_key="fan_min_speed",
                  canonical_key="filament.fan_min_speed",
                  recoverability="profile_only"),
            Field("filament.fan_always_on", "ファン常時オン", kind="bool",
                  default=True,
                  native_key="fan_always_on",
                  canonical_key="filament.fan_always_on",
                  recoverability="profile_only"),
            Field("filament.fan_off_first_layers", "最初のN層はファンオフ", "層", kind="int",
                  default=1,
                  native_key="fan_cooling_layer_time",     # 未確認
                  canonical_key="filament.fan_off_first_layers",
                  recoverability="profile_only"),
            Field("filament.bridge_fan_speed", "ブリッジファン速度", "%",
                  default=100.0,
                  native_key="bridge_fan_speed",
                  canonical_key="filament.bridge_fan_speed",
                  recoverability="profile_only",
                  visibility="advanced"),
            Field("filament.overhang_fan_speed", "オーバーハングファン速度", "%",
                  default=100.0,
                  native_key="overhang_fan_speed",
                  canonical_key="filament.overhang_fan_speed",
                  recoverability="profile_only",
                  visibility="advanced"),
            Field("filament.auxiliary_fan_speed", "補助ファン速度", "%",
                  default=0.0,
                  native_key="auxiliary_fan_speed",
                  canonical_key="filament.auxiliary_fan_speed",
                  recoverability="profile_only",
                  visibility="advanced"),
            Field("filament.chamber_fan_speed", "チャンバーファン速度", "%",
                  default=0.0,
                  native_key="chamber_fan_speed",          # 未確認
                  canonical_key="filament.chamber_fan_speed",
                  recoverability="profile_only",
                  visibility="advanced"),
            Field("filament.slow_down_for_cooling", "冷却のために減速", kind="bool",
                  default=True,
                  native_key="slow_down_for_layer_cooling",
                  canonical_key="filament.slow_down_for_cooling",
                  recoverability="profile_only"),
            Field("filament.min_layer_time", "最小層時間", "s",
                  default=5.0,
                  native_key="slow_down_layer_time",
                  canonical_key="filament.min_layer_time",
                  recoverability="profile_only",
                  enabled_if=["filament.slow_down_for_cooling"]),
            Field("filament.min_print_speed", "最小印刷速度", "mm/s",
                  default=10.0,
                  native_key="min_print_speed",
                  canonical_key="filament.min_print_speed",
                  recoverability="profile_only",
                  enabled_if=["filament.slow_down_for_cooling"]),
            Field("filament.full_fan_speed_layer", "最大ファン速度開始層", "層", kind="int",
                  default=4,
                  native_key="full_fan_speed_layer",
                  canonical_key="filament.full_fan_speed_layer",
                  recoverability="profile_only",
                  visibility="advanced"),
        ]),
    ]),
    # -----------------------------------------------------------------------
    SubTab("リトラクション上書き", [
        ("上書き (フィラメント個別設定)", [
            Field("filament.retract_length_override", "リトラクト長 (上書き)", "mm",
                  default=None,
                  native_key="retract_length",             # 未確認(filament-level)
                  canonical_key="filament.retract_length_override",
                  recoverability="profile_only",
                  per_tool=True,
                  description="空白 = プリンター設定を使用"),
            Field("filament.retract_speed_override", "リトラクト速度 (上書き)", "mm/s",
                  default=None,
                  canonical_key="filament.retract_speed_override",
                  recoverability="profile_only",
                  per_tool=True),
            Field("filament.deretract_speed_override", "戻し速度 (上書き)", "mm/s",
                  default=None,
                  canonical_key="filament.deretract_speed_override",
                  recoverability="profile_only",
                  per_tool=True),
            Field("filament.z_hop_override", "Zホップ高さ (上書き)", "mm",
                  default=None,
                  canonical_key="filament.z_hop_override",
                  recoverability="profile_only",
                  per_tool=True),
            Field("filament.wipe_override", "ワイプ (上書き)", kind="bool",
                  default=False,
                  canonical_key="filament.wipe_override",
                  recoverability="profile_only",
                  per_tool=True),
        ]),
    ]),
    # -----------------------------------------------------------------------
    SubTab("高度な設定", [
        ("Pressure Advance", [
            Field("filament.pressure_advance", "Pressure Advance", "",
                  default=0.0,
                  native_key="pressure_advance",
                  canonical_key="filament.pressure_advance",
                  recoverability="profile_only",
                  per_tool=True,
                  description="PA / Linear Advance / Pressure Advance の値。複数セクションには設定しない"),
        ]),
        ("G-code", [
            Field("filament.start_gcode", "filament start G-code", kind="gcode",
                  default="",
                  canonical_key="filament.gcode.start",
                  recoverability="profile_only",
                  visibility="advanced",
                  per_tool=True,
                  description="OrcaSlicer native_key は未確認"),
            Field("filament.end_gcode", "filament end G-code", kind="gcode",
                  default="",
                  canonical_key="filament.gcode.end",
                  recoverability="profile_only",
                  visibility="advanced",
                  per_tool=True,
                  description="OrcaSlicer native_key は未確認"),
        ]),
        ("体積流量制限", [
            Field("filament.max_volumetric_speed_limit", "最大体積流量制限", "mm³/s",
                  default=0.0,
                  native_key="filament_max_volumetric_speed",
                  canonical_key="filament.max_volumetric_speed_limit",
                  recoverability="profile_only",
                  description="0 = 無制限。filament.max_volumetric_speed と同じ OrcaSlicer キーを共有"),
            Field("filament.volumetric_speed_limit_enabled", "体積流量制限を有効化", kind="bool",
                  default=False,
                  canonical_key="filament.volumetric_speed_limit_enabled",
                  recoverability="profile_only",
                  visibility="advanced",
                  description="OrcaSlicer native_key は未確認"),
            Field("filament.volumetric_speed_soft_limit", "体積流量ソフト制限", "mm³/s",
                  default=0.0,
                  canonical_key="filament.volumetric_speed_soft_limit",
                  recoverability="profile_only",
                  visibility="expert",
                  enabled_if=["filament.volumetric_speed_limit_enabled"],
                  description="OrcaSlicer native_key は未確認"),
        ]),
        ("フィラメント交換", [
            Field("filament.load_time", "ロード時間", "s",
                  default=0.0,
                  native_key="filament_load_time",
                  canonical_key="filament.load_time",
                  recoverability="profile_only",
                  visibility="advanced"),
            Field("filament.unload_time", "アンロード時間", "s",
                  default=0.0,
                  native_key="filament_unload_time",
                  canonical_key="filament.unload_time",
                  recoverability="profile_only",
                  visibility="advanced"),
            Field("filament.ramming_parameters", "ramming parameters", "", kind="text",
                  default="",
                  canonical_key="filament.ramming.parameters",
                  recoverability="profile_only",
                  visibility="expert",
                  description="OrcaSlicer native_key は未確認"),
            Field("filament.ramming_volume", "ramming volume", "mm³",
                  default=0.0,
                  canonical_key="filament.ramming.volume",
                  recoverability="profile_only",
                  visibility="expert",
                  description="OrcaSlicer native_key は未確認"),
        ]),
    ]),
    # -----------------------------------------------------------------------
    SubTab("Multimaterial", special="per_filament"),
    SubTab("Notes", [
        ("メモ", [
            Field("filament.notes", "Notes", "", kind="text",
                  default="",
                  canonical_key="filament.notes",
                  recoverability="profile_only"),
        ]),
    ]),
]


GROUPS = {
    "printer": ("🖨  プリンター設定", PRINTER),
    "filament": ("◎  フィラメント設定", FILAMENT),
    "process": ("≣  プロセス設定", PROCESS),
}


def all_fields(schema):
    """スキーマ内の全 Field を yield する (special タブは除く)。"""
    for st in schema:
        for _sec, fields in st.sections:
            for f in fields:
                yield f


def default_values():
    """解析なしの既定値ストアと出所(全て default)を返す。"""
    values, prov = {}, {}
    for _gk, (_t, schema) in GROUPS.items():
        for f in all_fields(schema):
            if f.default is not None:
                values[f.key] = f.default
                prov[f.key] = "default"
    return values, prov


def prefill_values(result: dict):
    """解析結果から値ストアと出所を初期化する。
    返り値: (values, provenance)。
    provenance[key]: 'recovered'=G-codeから復元 / 'default'=取得できず既定値 /
                     'unknown'=不明 (値はあるが信頼性不明) / 'estimated'=低信頼度推定。
    unknown の値を recovered として表示しない。"""
    values, prov = default_values()

    def get(path):
        sec, fld = path.split(".", 1)
        return result.get(sec, {}).get(fld)

    for _gk, (_t, schema) in GROUPS.items():
        for f in all_fields(schema):
            if f.src:
                v = get(f.src)
                if v is not None:
                    values[f.key] = v
                    # low_conf フィールドは 'estimated'、それ以外は 'recovered'
                    prov[f.key] = "estimated" if f.low_conf else "recovered"

    # G-codeスタイルの推定(復元扱い)
    fs = result.get("meta", {}).get("feature_style", "")
    if "産業機" in fs:
        values["machine.gcode_flavor"] = "産業機(独自)"
        prov["machine.gcode_flavor"] = "recovered"

    return values, prov
